defmodule InfluxElixir.Contract.InfluxQLGlueCases do
  @moduledoc "Statements over the `~p1` fixture of `InfluxElixir.Contract.InfluxQLProjectionCases` with the answers InfluxDB 3 Core 3.10.1 gave when a keyword stands directly against the character after it (a `WHERE`, `SELECT` or `FROM` against a parenthesis, a sign, a slash, a quote or `*`; `LIMIT`, `OFFSET`, `SLIMIT`, `SOFFSET` and `GROUP BY` against a parenthesis or a sign; a `SHOW` keyword against a quote), when a quote, quoted name or regular expression is never closed where the parser reads no token (`LIMIT 'x`, `ON 'x`, a statement that starts with a quote) and where it does (`FROM \"x`, a `WHERE`), and for `tz()` where an operand is wanted. The statements the double refuses by name, with the reason pinned, are `refusals/0`."

  alias InfluxElixir.Contract.InfluxQLDefectCases

  @doc "The names the cases use, from one unique `prefix`: `~p1`."
  @spec names(binary()) :: %{binary() => binary()}
  defdelegate names(prefix), to: InfluxQLDefectCases

  @doc "The fixture, as line protocol, with `names/1` substituted."
  @spec fixture(%{binary() => binary()}) :: [binary()]
  defdelegate fixture(names), to: InfluxQLDefectCases

  @doc "Statements the double answers as the engine does."
  @spec forms() :: [{binary(), term()}]
  def forms do
    [
      {"SELECT usage FROM ~p1 WHERE(host = 'zz')", []},
      {"SELECT usage FROM ~p1 WHERE+1 = 1 AND time < '2023-10-01T00:01:00Z'",
       [{"2023-10-01 00:00:00", %{"usage" => 0.25}}]},
      {"SELECT usage FROM ~p1 WHERE-1 = host", []},
      {"SELECT usage FROM ~p1 WHERE(host = 'zz')AND(region = 'zz')", []},
      {"SELECT usage FROM ~p1 WHERE(host = 'a')AND(region = 'us')AND time < '2023-10-01T00:01:00Z'",
       [{"2023-10-01 00:00:00", %{"usage" => 0.25}}]},
      {"SELECT*FROM ~p1 WHERE time < '2023-10-01T00:01:00Z'",
       [
         {"2023-10-01 00:00:00",
          %{"host" => "a", "n" => -10, "ok" => true, "region" => "us", "u" => 1, "usage" => 0.25}}
       ]},
      {"SELECT(usage)FROM ~p1 WHERE time < '2023-10-01T00:01:00Z'",
       [{"2023-10-01 00:00:00", %{"usage" => 0.25}}]},
      {"SELECT usage,(n)FROM ~p1 WHERE time < '2023-10-01T00:01:00Z'",
       [{"2023-10-01 00:00:00", %{"n" => -10, "usage" => 0.25}}]},
      {"SELECT \"usage\"FROM ~p1 WHERE time < '2023-10-01T00:01:00Z'",
       [{"2023-10-01 00:00:00", %{"usage" => 0.25}}]},
      {"SELECT usage FROM/~p1/ WHERE time < '2023-10-01T00:01:00Z'",
       [{"2023-10-01 00:00:00", %{"usage" => 0.25}}]},
      {"SELECT usage FROM/^~p1$/ WHERE time < '2023-10-01T00:01:00Z'",
       [{"2023-10-01 00:00:00", %{"usage" => 0.25}}]},
      {"SELECT usage FROM ~p1 WHERE time < '2023-10-01T00:01:00Z'",
       [{"2023-10-01 00:00:00", %{"usage" => 0.25}}]},
      {"SELECT usage FROM\"~p1\" WHERE time < '2023-10-01T00:01:00Z'",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 0. Parsing Error: Nom(\"SELECT usage FROM\\\"~p1\\\" WHERE time < '2023-10-01T00:01:00Z'\", Tag)"}},
      {"SELECT usage FROM'~p1' WHERE time < '2023-10-01T00:01:00Z'",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 0. Parsing Error: Nom(\"SELECT usage FROM'~p1' WHERE time < '2023-10-01T00:01:00Z'\", Tag)"}},
      {"SELECT usage FROM ~p1 GROUP BY(host)",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"GROUP BY(host)\", Tag)"}},
      {"SELECT usage FROM ~p1 LIMIT(1)",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"LIMIT(1)\", Tag)"}},
      {"SELECT usage FROM ~p1 LIMIT-1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"LIMIT-1\", Tag)"}},
      {"SELECT usage FROM ~p1 LIMIT+1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"LIMIT+1\", Tag)"}},
      {"SELECT usage FROM ~p1 OFFSET(1)",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"OFFSET(1)\", Tag)"}},
      {"SELECT usage FROM ~p1 LIMIT 1 OFFSET(1)",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 30. Parsing Error: Nom(\"OFFSET(1)\", Tag)"}},
      {"SELECT usage FROM ~p1 SLIMIT(1)",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"SLIMIT(1)\", Tag)"}},
      {"SELECT usage FROM ~p1 SOFFSET-1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"SOFFSET-1\", Tag)"}},
      {"SELECT usage FROM ~p1 WHERE usage = 1 OR tz('UTC')",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid expression, the only valid function calls are 'now' with no arguments, date_part(<literal>, time), or scalar math functions at pos 41"}},
      {"SELECT usage FROM ~p1 WHERE usage = 1 AND tz('UTC')",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid expression, the only valid function calls are 'now' with no arguments, date_part(<literal>, time), or scalar math functions at pos 42"}},
      {"SELECT usage FROM ~p1 WHERE usage = 1 + tz('UTC')",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid expression, the only valid function calls are 'now' with no arguments, date_part(<literal>, time), or scalar math functions at pos 40"}},
      {"SELECT usage FROM ~p1 WHERE tz ( 'UTC' )",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid expression, the only valid function calls are 'now' with no arguments, date_part(<literal>, time), or scalar math functions at pos 28"}},
      {"SELECT usage FROM ~p1 WHERE (usage = 1 OR tz('UTC'))",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid expression, the only valid function calls are 'now' with no arguments, date_part(<literal>, time), or scalar math functions at pos 42"}},
      {"'",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 0. Parsing Error: Nom(\"'\", Tag)"}},
      {"'x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 0. Parsing Error: Nom(\"'x\", Tag)"}},
      {"\"x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 0. Parsing Error: Nom(\"\\\"x\", Tag)"}},
      {"/x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 0. Parsing Error: Nom(\"/x\", Tag)"}},
      {" 'x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 1. Parsing Error: Nom(\"'x\", Tag)"}},
      {"SHOW DATABASES\"",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid SHOW statement, expected DATABASES, FIELD KEYS, MEASUREMENTS, TAG KEYS, TAG VALUES, or RETENTION POLICIES following SHOW at pos 5"}},
      {"SHOW DATABASES'",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid SHOW statement, expected DATABASES, FIELD KEYS, MEASUREMENTS, TAG KEYS, TAG VALUES, or RETENTION POLICIES following SHOW at pos 5"}},
      {"SHOW DATABASES 'x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 15. Parsing Error: Nom(\"'x\", Tag)"}},
      {"SHOW DATABASES \"x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 15. Parsing Error: Nom(\"\\\"x\", Tag)"}},
      {"SHOW TAG KEYS FROM ~p1'",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"'\", Tag)"}},
      {"SHOW TAG KEYS FROM ~p1\"",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"\\\"\", Tag)"}},
      {"SHOW TAG KEYS FROM ~p1 'x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 23. Parsing Error: Nom(\"'x\", Tag)"}},
      {"SHOW TAG VALUES WITH KEY\"= a",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid WITH KEY clause, expected KEY at pos 21"}},
      {"SHOW TAG VALUES WITH KEY'= a",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid WITH KEY clause, expected KEY at pos 21"}},
      {"SHOW TAG KEYS FROM/~p1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 14. Parsing Error: Nom(\"FROM/~p1\", Tag)"}},
      {"SHOW TAG KEYS FROM/~p1/",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 14. Parsing Error: Nom(\"FROM/~p1/\", Tag)"}},
      {"SHOW TAG KEYS FROM\"~p1\"",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 14. Parsing Error: Nom(\"FROM\\\"~p1\\\"\", Tag)"}},
      {"SHOW TAG KEYS FROM'~p1'",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 14. Parsing Error: Nom(\"FROM'~p1'\", Tag)"}},
      {"SHOW TAG KEYS'",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid SHOW TAG statement, expected KEYS or VALUES at pos 9"}},
      {"SHOW TAG 'x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid SHOW TAG statement, expected KEYS or VALUES at pos 9"}},
      {"SHOW FIELD 'x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid SHOW FIELD KEYS statement, expected KEYS at pos 11"}},
      {"SHOW TAG VALUES 'x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid SHOW TAG VALUES statement, expected WITH KEY clause at pos 15"}},
      {"SHOW TAG VALUES WITH 'x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid WITH KEY clause, expected KEY at pos 21"}},
      {"SHOW TAG KEYS LIMIT'x'",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 14. Parsing Error: Nom(\"LIMIT'x'\", Tag)"}},
      {"SHOW TAG KEYS WHERE'a'='a'",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 14. Parsing Error: Nom(\"WHERE'a'='a'\", Tag)"}},
      {"SHOW TAG KEYS FROM ~p1 LIMIT 'x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid LIMIT clause, expected unsigned integer at pos 29"}},
      {"SHOW MEASUREMENTS LIMIT \"x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid LIMIT clause, expected unsigned integer at pos 24"}},
      {"SHOW MEASUREMENTS OFFSET 'x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid OFFSET clause, expected unsigned integer at pos 25"}},
      {"SHOW MEASUREMENTS ON 'x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid ON clause, expected wildcard or identifier at pos 21"}},
      {"SHOW MEASUREMENTS WITH MEASUREMENT = 'x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: expected measurement name at pos 37"}},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ 'x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: expected measurement name at pos 36"}},
      {"SHOW TAG VALUES WITH KEY = 'x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid WITH KEY clause, expected identifier following = at pos 26"}},
      {"SHOW TAG VALUES WITH KEY IN ('x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid IN clause, expected identifier at pos 29"}},
      {"SHOW TAG VALUES WITH KEY =~ 'x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid WITH KEY clause, expected regular expression following =~ at pos 28"}},
      {"SHOW MEASUREMENTS ON \"x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: unterminated string literal at pos 23"}},
      {"SHOW MEASUREMENTS WITH MEASUREMENT = \"x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: unterminated string literal at pos 39"}},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: unterminated regex literal at pos 40"}},
      {"SHOW MEASUREMENTS WITH MEASUREMENT = /x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: unterminated regex literal at pos 39"}},
      {"SHOW TAG KEYS FROM \"x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: unterminated string literal at pos 21"}},
      {"SHOW TAG KEYS FROM /x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: unterminated regex literal at pos 21"}},
      {"SHOW TAG KEYS FROM ~p1, \"x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: unterminated string literal at pos 26"}},
      {"SHOW TAG VALUES WITH KEY = \"x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: unterminated string literal at pos 29"}},
      {"SHOW TAG VALUES WITH KEY =~ /x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: unterminated regex literal at pos 30"}},
      {"SHOW MEASUREMENTS WHERE a = 'x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: unterminated string literal at pos 30"}},
      {"SHOW MEASUREMENTS WHERE 'x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: unterminated string literal at pos 26"}},
      {"SHOW MEASUREMENTS ON 5 WHERE a = 'x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid ON clause, expected wildcard or identifier at pos 21"}},
      {"SHOW MEASUREMENTS WHERE(a = 1)", []},
      {"SHOW MEASUREMENTS WHERE+a = 1", []},
      {"SHOW MEASUREMENTS WHERE-1 = a", []},
      {"SHOW TAG KEYS WHERE(a = 'x')", []},
      {"SHOW TAG KEYS FROM ~p1 WHERE(host = 'a')", []},
      {"SHOW MEASUREMENTS WHERE=1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 18. Parsing Error: Nom(\"WHERE=1\", Tag)"}},
      {"SHOW MEASUREMENTS WHERE*1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 18. Parsing Error: Nom(\"WHERE*1\", Tag)"}},
      {"SHOW MEASUREMENTS WHERE/x/",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 18. Parsing Error: Nom(\"WHERE/x/\", Tag)"}},
      {"SHOW MEASUREMENTS WHERE)",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 18. Parsing Error: Nom(\"WHERE)\", Tag)"}},
      {"SHOW MEASUREMENTS WHERE<1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 18. Parsing Error: Nom(\"WHERE<1\", Tag)"}},
      {"SHOW MEASUREMENTS WHERE;",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 18. Parsing Error: Nom(\"WHERE;\", Tag)"}}
    ]
  end

  @doc "Statements the engine answers (or rejects with a body the double does not give) and the double refuses by name, with the engine's answer."
  @spec refusals() :: [{binary(), term()}]
  def refusals do
    [
      {"SELECT usage FROM(SELECT usage FROM ~p1) WHERE time < '2023-10-01T00:01:00Z'",
       [{"2023-10-01 00:00:00", %{"usage" => 0.25}}]},
      {"SELECT 1FROM ~p1",
       {:error, 400,
        "rewriting statement\ncaused by\ngather information about select statement\ncaused by\nError during planning: field must contain at least one variable"}},
      {"SELECT usage+1FROM ~p1 WHERE time < '2023-10-01T00:01:00Z'",
       [{"2023-10-01 00:00:00", %{"usage" => 1.25}}]},
      {"SELECT usage FROM ~p1 'x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"'x\", Tag)"}},
      {"SELECT usage FROM ~p1 LIMIT 1 'x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 30. Parsing Error: Nom(\"'x\", Tag)"}},
      {"SELECT usage FROM ~p1 junk 'x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"junk 'x\", Tag)"}},
      {"SELECT usage AS x FROM ~p1 ORDER BY time AS#C",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 41. Parsing Error: Nom(\"AS#C\", Tag)"}},
      {"SELECT usage FROM ~p1 ORDER BY time ASC 'x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 40. Parsing Error: Nom(\"'x\", Tag)"}},
      {"SELECT usage FROM ~p1 WHERE ((usage > 0 AND n < 0)) OR ((usage > 5)) AND time < '2023-10-01T00:01:00Z'",
       [{"2023-10-01 00:00:00", %{"usage" => 0.25}}]}
    ]
  end

  @doc "The reason the double gives for each statement of `refusals/0` (`Client.Local: <reason>`, with the statement after it when the parser refuses)."
  @spec refusal_reasons() :: %{binary() => binary()}
  def refusal_reasons do
    %{
      "SELECT usage FROM(SELECT usage FROM ~p1) WHERE time < '2023-10-01T00:01:00Z'" =>
        "unsupported InfluxQL (subqueries)",
      "SELECT 1FROM ~p1" => "unsupported InfluxQL (a number directly against FROM)",
      "SELECT usage+1FROM ~p1 WHERE time < '2023-10-01T00:01:00Z'" =>
        "unsupported InfluxQL (a number directly against FROM)",
      "SELECT usage FROM ~p1 'x" =>
        "unsupported InfluxQL (clauses the double does not read in that order)",
      "SELECT usage FROM ~p1 LIMIT 1 'x" =>
        "unsupported InfluxQL (clauses the double does not read in that order)",
      "SELECT usage FROM ~p1 junk 'x" =>
        "unsupported InfluxQL (clauses the double does not read in that order)",
      "SELECT usage AS x FROM ~p1 ORDER BY time AS#C" =>
        "unsupported InfluxQL (clauses the double does not read in that order)",
      "SELECT usage FROM ~p1 ORDER BY time ASC 'x" =>
        "unsupported InfluxQL (clauses the double does not read in that order)",
      "SELECT usage FROM ~p1 WHERE ((usage > 0 AND n < 0)) OR ((usage > 5)) AND time < '2023-10-01T00:01:00Z'" =>
        "unsupported InfluxQL (a time comparison inside OR)"
    }
  end

  @doc "A clause keyword, `AS` or `ON` directly against the character after it: `LIMIT`, `OFFSET`, `SLIMIT`, `SOFFSET` and `WHERE` read nothing glued to a character that is no blank, `GROUP BY` and `ORDER BY` split the characters in two (operators and parentheses against any other), `AS` and `ON` likewise; also a quote or a regular expression where a `fill()` option or `ASC` is read, and the parentheses of a `WHERE` kept and nested."
  @spec keyword_glue() :: [{binary(), term()}]
  def keyword_glue do
    [
      {"SELECT usage FROM ~p1 LIMIT\"1\"",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"LIMIT\\\"1\\\"\", Tag)"}},
      {"SELECT usage FROM ~p1 LIMIT'1'",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"LIMIT'1'\", Tag)"}},
      {"SELECT usage FROM ~p1 LIMIT/1/",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"LIMIT/1/\", Tag)"}},
      {"SELECT usage FROM ~p1 LIMIT*",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"LIMIT*\", Tag)"}},
      {"SELECT usage FROM ~p1 LIMIT$p",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"LIMIT$p\", Tag)"}},
      {"SELECT usage FROM ~p1 LIMIT.1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"LIMIT.1\", Tag)"}},
      {"SELECT usage FROM ~p1 LIMIT=1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"LIMIT=1\", Tag)"}},
      {"SELECT usage FROM ~p1 LIMITx",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"LIMITx\", Tag)"}},
      {"SELECT usage FROM ~p1 LIMIT11",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"LIMIT11\", Tag)"}},
      {"SELECT usage FROM ~p1 OFFSET\"1\"",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"OFFSET\\\"1\\\"\", Tag)"}},
      {"SELECT usage FROM ~p1 OFFSET'1'",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"OFFSET'1'\", Tag)"}},
      {"SELECT usage FROM ~p1 OFFSET/1/",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"OFFSET/1/\", Tag)"}},
      {"SELECT usage FROM ~p1 OFFSET*",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"OFFSET*\", Tag)"}},
      {"SELECT usage FROM ~p1 OFFSET$p",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"OFFSET$p\", Tag)"}},
      {"SELECT usage FROM ~p1 OFFSET.1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"OFFSET.1\", Tag)"}},
      {"SELECT usage FROM ~p1 OFFSET=1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"OFFSET=1\", Tag)"}},
      {"SELECT usage FROM ~p1 OFFSETx",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"OFFSETx\", Tag)"}},
      {"SELECT usage FROM ~p1 OFFSET11",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"OFFSET11\", Tag)"}},
      {"SELECT usage FROM ~p1 SLIMIT\"1\"",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"SLIMIT\\\"1\\\"\", Tag)"}},
      {"SELECT usage FROM ~p1 SLIMIT'1'",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"SLIMIT'1'\", Tag)"}},
      {"SELECT usage FROM ~p1 SLIMIT/1/",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"SLIMIT/1/\", Tag)"}},
      {"SELECT usage FROM ~p1 SLIMIT*",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"SLIMIT*\", Tag)"}},
      {"SELECT usage FROM ~p1 SLIMIT$p",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"SLIMIT$p\", Tag)"}},
      {"SELECT usage FROM ~p1 SLIMIT.1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"SLIMIT.1\", Tag)"}},
      {"SELECT usage FROM ~p1 SLIMIT=1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"SLIMIT=1\", Tag)"}},
      {"SELECT usage FROM ~p1 SLIMITx",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"SLIMITx\", Tag)"}},
      {"SELECT usage FROM ~p1 SLIMIT11",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"SLIMIT11\", Tag)"}},
      {"SELECT usage FROM ~p1 SOFFSET\"1\"",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"SOFFSET\\\"1\\\"\", Tag)"}},
      {"SELECT usage FROM ~p1 SOFFSET'1'",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"SOFFSET'1'\", Tag)"}},
      {"SELECT usage FROM ~p1 SOFFSET/1/",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"SOFFSET/1/\", Tag)"}},
      {"SELECT usage FROM ~p1 SOFFSET*",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"SOFFSET*\", Tag)"}},
      {"SELECT usage FROM ~p1 SOFFSET$p",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"SOFFSET$p\", Tag)"}},
      {"SELECT usage FROM ~p1 SOFFSET.1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"SOFFSET.1\", Tag)"}},
      {"SELECT usage FROM ~p1 SOFFSET=1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"SOFFSET=1\", Tag)"}},
      {"SELECT usage FROM ~p1 SOFFSETx",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"SOFFSETx\", Tag)"}},
      {"SELECT usage FROM ~p1 SOFFSET11",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"SOFFSET11\", Tag)"}},
      {"SELECT usage FROM ~p1 LIMIT 1 OFFSET\"1\"",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 30. Parsing Error: Nom(\"OFFSET\\\"1\\\"\", Tag)"}},
      {"SELECT usage FROM ~p1 LIMIT 1 SLIMIT'1'",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 30. Parsing Error: Nom(\"SLIMIT'1'\", Tag)"}},
      {"SELECT usage FROM ~p1 GROUP BY host SLIMIT 1 SOFFSET*",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 45. Parsing Error: Nom(\"SOFFSET*\", Tag)"}},
      {"SELECT usage,/n/FROM ~p1 WHERE time < '2023-10-01T00:01:00Z'",
       [{"2023-10-01 00:00:00", %{"n" => -10, "region" => "us", "usage" => 0.25}}]},
      {"SELECT usage AS/x/ FROM ~p1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid field alias, expected identifier at pos 15"}},
      {"SELECT usage AS\"x\" FROM ~p1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 0. Parsing Error: Nom(\"SELECT usage AS\\\"x\\\" FROM ~p1\", Tag)"}},
      {"SELECT usage AS'x' FROM ~p1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 0. Parsing Error: Nom(\"SELECT usage AS'x' FROM ~p1\", Tag)"}},
      {"SELECT usage AS.x FROM ~p1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 0. Parsing Error: Nom(\"SELECT usage AS.x FROM ~p1\", Tag)"}},
      {"SELECT usage AS$x FROM ~p1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 0. Parsing Error: Nom(\"SELECT usage AS$x FROM ~p1\", Tag)"}},
      {"SELECT usage AS*x FROM ~p1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid field alias, expected identifier at pos 15"}},
      {"SELECT usage AS(x FROM ~p1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid field alias, expected identifier at pos 15"}},
      {"SELECT usage AS)x FROM ~p1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid field alias, expected identifier at pos 15"}},
      {"SELECT usage AS=x FROM ~p1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid field alias, expected identifier at pos 15"}},
      {"SELECT usage AS@x FROM ~p1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 0. Parsing Error: Nom(\"SELECT usage AS@x FROM ~p1\", Tag)"}},
      {"SELECT mean(usage) FROM ~p1 GROUP BY time(1m) fill'null)",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 46. Parsing Error: Nom(\"fill'null)\", Tag)"}},
      {"SELECT mean(usage) FROM ~p1 GROUP BY time(1m) fill\"null)",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 46. Parsing Error: Nom(\"fill\\\"null)\", Tag)"}},
      {"SELECT usage FROM ~p1 GROUP BY\"host\"",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid GROUP BY clause, expected BY at pos 28"}},
      {"SELECT usage FROM ~p1 GROUP BY'host'",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid GROUP BY clause, expected BY at pos 28"}},
      {"SELECT usage FROM ~p1 GROUP BY$p",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid GROUP BY clause, expected BY at pos 28"}},
      {"SELECT usage FROM ~p1 GROUP BY.host",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid GROUP BY clause, expected BY at pos 28"}},
      {"SELECT usage FROM ~p1 GROUP BY/host/",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"GROUP BY/host/\", Tag)"}},
      {"SELECT usage FROM ~p1 GROUP BY*",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"GROUP BY*\", Tag)"}},
      {"SELECT usage FROM ~p1 GROUP BY=host",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"GROUP BY=host\", Tag)"}},
      {"SELECT usage FROM ~p1 GROUP BY,host",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"GROUP BY,host\", Tag)"}},
      {"SELECT usage FROM ~p1 GROUP BY<host",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"GROUP BY<host\", Tag)"}},
      {"SELECT usage FROM ~p1 GROUP BY)host",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"GROUP BY)host\", Tag)"}},
      {"SELECT usage FROM ~p1 GROUP BY%host",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"GROUP BY%host\", Tag)"}},
      {"SELECT usage FROM ~p1 GROUP BY~host",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid GROUP BY clause, expected BY at pos 28"}},
      {"SELECT usage FROM ~p1 GROUP BY@host",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid GROUP BY clause, expected BY at pos 28"}},
      {"SELECT usage FROM ~p1 GROUP BY[host",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid GROUP BY clause, expected BY at pos 28"}},
      {"SELECT usage FROM ~p1 GROUP BY{host",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid GROUP BY clause, expected BY at pos 28"}},
      {"SELECT usage FROM ~p1 GROUP BY1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid GROUP BY clause, expected BY at pos 28"}},
      {"SELECT usage FROM ~p1 WHERE usage > 1 GROUP BY\"host\"",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid GROUP BY clause, expected BY at pos 44"}},
      {"SELECT usage FROM ~p1 GROUP BY host LIMIT\"1\"",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 36. Parsing Error: Nom(\"LIMIT\\\"1\\\"\", Tag)"}},
      {"SELECT usage FROM ~p1 WHERE\"1\"",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"WHERE\\\"1\\\"\", Tag)"}},
      {"SELECT usage FROM ~p1 WHERE.5",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"WHERE.5\", Tag)"}},
      {"SELECT usage FROM ~p1 WHEREx",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"WHEREx\", Tag)"}},
      {"SELECT usage FROM ~p1 WHERE$p",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"WHERE$p\", Tag)"}},
      {"SELECT usage FROM ~p1 WHERE~1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"WHERE~1\", Tag)"}},
      {"SELECT usage FROM ~p1 ORDER BY\"time\"",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"ORDER BY\\\"time\\\"\", Tag)"}},
      {"SELECT usage FROM ~p1 ORDER BY'time'",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"ORDER BY'time'\", Tag)"}},
      {"SELECT usage FROM ~p1 ORDER BY$time",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"ORDER BY$time\", Tag)"}},
      {"SELECT usage FROM ~p1 ORDER BY.time",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"ORDER BY.time\", Tag)"}},
      {"SELECT usage FROM ~p1 ORDER BY:time",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"ORDER BY:time\", Tag)"}},
      {"SELECT usage FROM ~p1 ORDER BY~time",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"ORDER BY~time\", Tag)"}},
      {"SELECT usage FROM ~p1 ORDER BYxtime",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"ORDER BYxtime\", Tag)"}},
      {"SELECT usage FROM ~p1 ORDER BY@time",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"ORDER BY@time\", Tag)"}},
      {"SELECT usage FROM ~p1 ORDER BY#time",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"ORDER BY#time\", Tag)"}},
      {"SELECT usage FROM ~p1 ORDER BY[time",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"ORDER BY[time\", Tag)"}},
      {"SELECT usage FROM ~p1 ORDER BY/time",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid ORDER BY, expected ASC, DESC or TIME at pos 30"}},
      {"SELECT usage FROM ~p1 ORDER BY*time",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid ORDER BY, expected ASC, DESC or TIME at pos 30"}},
      {"SELECT usage FROM ~p1 ORDER BY(time)",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid ORDER BY, expected ASC, DESC or TIME at pos 30"}},
      {"SELECT usage FROM ~p1 ORDER BY=time",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid ORDER BY, expected ASC, DESC or TIME at pos 30"}},
      {"SELECT usage FROM ~p1 WHERE (usage > 0) AND (n < 0) AND time < '2023-10-01T00:01:00Z'",
       [{"2023-10-01 00:00:00", %{"usage" => 0.25}}]},
      {"SELECT usage FROM ~p1 WHERE (usage + 1) > 1 AND (n) < 0 AND time < '2023-10-01T00:01:00Z'",
       [{"2023-10-01 00:00:00", %{"usage" => 0.25}}]},
      {"SELECT usage FROM ~p1 WHERE ((((usage > 0)))) AND time < '2023-10-01T00:01:00Z'",
       [{"2023-10-01 00:00:00", %{"usage" => 0.25}}]},
      {"SELECT usage FROM ~p1 WHERE (usage > 0",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"WHERE (usage > 0\", Tag)"}},
      {"SELECT usage FROM ~p1 WHERE ((usage > 0)",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"WHERE ((usage > 0)\", Tag)"}},
      {"SELECT usage FROM ~p1 WHERE (usage > 0))",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 39. Parsing Error: Nom(\")\", Tag)"}},
      {"SELECT usage FROM ~p1 WHERE usage > 0 AND (n < 1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid conditional expression at pos 41"}},
      {"SELECT usage FROM ~p1 WHERE (usage > 0 AND) n < 1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid conditional expression at pos 42"}},
      {"SELECT usage FROM ~p1 WHERE (usage > 0) n < 1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 40. Parsing Error: Nom(\"n < 1\", Tag)"}},
      {"SELECT usage FROM ~p1 WHERE (usage > 0) AND",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid conditional expression at pos 43"}},
      {"SELECT usage FROM ~p1 WHERE usage > 0 ) AND n < 1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 38. Parsing Error: Nom(\") AND n < 1\", Tag)"}},
      {"SHOW TAG KEYS ON'db'",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 14. Parsing Error: Nom(\"ON'db'\", Tag)"}},
      {"SHOW FIELD KEYS ON'db'",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 16. Parsing Error: Nom(\"ON'db'\", Tag)"}},
      {"SHOW RETENTION POLICIES ON'db'",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 24. Parsing Error: Nom(\"ON'db'\", Tag)"}},
      {"SHOW TAG KEYS ON$db",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 14. Parsing Error: Nom(\"ON$db\", Tag)"}},
      {"SHOW FIELD KEYS ON$db",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 16. Parsing Error: Nom(\"ON$db\", Tag)"}},
      {"SHOW RETENTION POLICIES ON$db",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 24. Parsing Error: Nom(\"ON$db\", Tag)"}},
      {"SHOW TAG KEYS ON:db",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 14. Parsing Error: Nom(\"ON:db\", Tag)"}},
      {"SHOW FIELD KEYS ON:db",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 16. Parsing Error: Nom(\"ON:db\", Tag)"}},
      {"SHOW RETENTION POLICIES ON:db",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 24. Parsing Error: Nom(\"ON:db\", Tag)"}},
      {"SHOW TAG KEYS ON~db",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 14. Parsing Error: Nom(\"ON~db\", Tag)"}},
      {"SHOW FIELD KEYS ON~db",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 16. Parsing Error: Nom(\"ON~db\", Tag)"}},
      {"SHOW RETENTION POLICIES ON~db",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 24. Parsing Error: Nom(\"ON~db\", Tag)"}},
      {"SHOW TAG KEYS ON[db",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 14. Parsing Error: Nom(\"ON[db\", Tag)"}},
      {"SHOW FIELD KEYS ON[db",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 16. Parsing Error: Nom(\"ON[db\", Tag)"}},
      {"SHOW RETENTION POLICIES ON[db",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 24. Parsing Error: Nom(\"ON[db\", Tag)"}},
      {"SHOW TAG KEYS ON@db",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 14. Parsing Error: Nom(\"ON@db\", Tag)"}},
      {"SHOW FIELD KEYS ON@db",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 16. Parsing Error: Nom(\"ON@db\", Tag)"}},
      {"SHOW RETENTION POLICIES ON@db",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 24. Parsing Error: Nom(\"ON@db\", Tag)"}},
      {"SHOW TAG KEYS ON#db",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 14. Parsing Error: Nom(\"ON#db\", Tag)"}},
      {"SHOW FIELD KEYS ON#db",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 16. Parsing Error: Nom(\"ON#db\", Tag)"}},
      {"SHOW RETENTION POLICIES ON#db",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 24. Parsing Error: Nom(\"ON#db\", Tag)"}},
      {"SHOW TAG KEYS ON{db",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 14. Parsing Error: Nom(\"ON{db\", Tag)"}},
      {"SHOW FIELD KEYS ON{db",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 16. Parsing Error: Nom(\"ON{db\", Tag)"}},
      {"SHOW RETENTION POLICIES ON{db",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 24. Parsing Error: Nom(\"ON{db\", Tag)"}},
      {"SHOW TAG KEYS ON`db",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 14. Parsing Error: Nom(\"ON`db\", Tag)"}},
      {"SHOW FIELD KEYS ON`db",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 16. Parsing Error: Nom(\"ON`db\", Tag)"}},
      {"SHOW RETENTION POLICIES ON`db",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 24. Parsing Error: Nom(\"ON`db\", Tag)"}},
      {"SHOW TAG KEYS ON*",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid ON clause, expected identifier at pos 16"}},
      {"SHOW TAG KEYS ON(db)",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid ON clause, expected identifier at pos 16"}},
      {"SELECT usage FROM ~p1 WHERE'a'='a'",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"WHERE'a'='a'\", Tag)"}},
      {"SELECT usage FROM ~p1 WHERE*1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"WHERE*1\", Tag)"}},
      {"SELECT usage FROM ~p1 WHERE=1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"WHERE=1\", Tag)"}},
      {"SELECT usage FROM ~p1 WHERE)",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"WHERE)\", Tag)"}}
    ]
  end

  @doc "A regular expression for columns directly against `FROM`, `AS` or an operator."
  @spec regex_columns() :: [{binary(), term()}]
  def regex_columns do
    [
      {"SELECT /usage/FROM ~p1 WHERE time < '2023-10-01T00:01:00Z'",
       [{"2023-10-01 00:00:00", %{"usage" => 0.25}}]},
      {"SELECT /usage/,/n/FROM ~p1 WHERE time < '2023-10-01T00:01:00Z'",
       [{"2023-10-01 00:00:00", %{"n" => -10, "region" => "us", "usage" => 0.25}}]},
      {"SELECT /usage/AS x FROM ~p1 WHERE time < '2023-10-01T00:01:00Z'",
       [{"2023-10-01 00:00:00", %{"usage" => 0.25}}]},
      {"SELECT /usage/FROM/~p1/ WHERE time < '2023-10-01T00:01:00Z'",
       [{"2023-10-01 00:00:00", %{"usage" => 0.25}}]},
      {"SELECT /usage/-FROM ~p1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 0. Parsing Failure: Nom(\"FROM ~p1\", Char)"}},
      {"SELECT /usage/+FROM ~p1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 0. Parsing Failure: Nom(\"FROM ~p1\", Char)"}},
      {"SELECT /usage/*FROM ~p1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 0. Parsing Error: Nom(\"SELECT /usage/*FROM ~p1\", Tag)"}},
      {"SELECT /usage//FROM ~p1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 0. Parsing Error: Nom(\"SELECT /usage//FROM ~p1\", Tag)"}},
      {"SELECT /usage/ x FROM ~p1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 0. Parsing Error: Nom(\"SELECT /usage/ x FROM ~p1\", Tag)"}},
      {"SELECT /usage/(w) FROM ~p1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 0. Parsing Error: Nom(\"SELECT /usage/(w) FROM ~p1\", Tag)"}},
      {"SELECT /usage/ AS /x/FROM ~p1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid field alias, expected identifier at pos 17"}}
    ]
  end

  @doc "A `::` with a type the engine does not know, glued to `FROM` or not, and the casts it reads."
  @spec casts() :: [{binary(), term()}]
  def casts do
    [
      {"SELECT *::fieldFROM ~p1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid wildcard type specifier, expected TAG or FIELD at pos 10"}},
      {"SELECT usage::fieldFROM ~p1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid data type for tag or field reference, expected float, integer, unsigned, string, boolean, field, tag at pos 14"}},
      {"SELECT usage::tagFROM ~p1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid data type for tag or field reference, expected float, integer, unsigned, string, boolean, field, tag at pos 14"}},
      {"SELECT usage::foo FROM ~p1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid data type for tag or field reference, expected float, integer, unsigned, string, boolean, field, tag at pos 14"}},
      {"SELECT *::foo FROM ~p1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid wildcard type specifier, expected TAG or FIELD at pos 10"}},
      {"SELECT usage::1 FROM ~p1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid data type for tag or field reference, expected float, integer, unsigned, string, boolean, field, tag at pos 14"}},
      {"SELECT mean(usage::foo) FROM ~p1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid data type for tag or field reference, expected float, integer, unsigned, string, boolean, field, tag at pos 19"}},
      {"SELECT usage,*::fooFROM ~p1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid wildcard type specifier, expected TAG or FIELD at pos 16"}},
      {"SELECT usage::fieldFROM",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid data type for tag or field reference, expected float, integer, unsigned, string, boolean, field, tag at pos 14"}},
      {"SELECT /usage/::fieldFROM ~p1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 0. Parsing Error: Nom(\"SELECT /usage/::fieldFROM ~p1\", Tag)"}}
    ]
  end
end
