defmodule InfluxElixir.Contract.InfluxQLShowCases do
  @moduledoc "The fixture and the statements of the InfluxQL `SHOW` contract, with the answers InfluxDB 3 Core gave."

  @doc """
  The names the cases use, from one unique `prefix`: `~p` is the prefix every
  measurement name starts with, `~m1` to `~m7`, `~mw` and `~mt` the measurements of
  `fixture/1` (`~mw` has three variants with a hyphen, a dot and a space) and
  `~db` the database the statements run in, which the caller adds.
  """
  @spec names(binary()) :: %{binary() => binary()}
  def names(prefix) do
    for key <- ~w(m1 m2 m3 m4 m5 m6 m7 mw mt), into: %{"p" => prefix} do
      {key, prefix <> "_" <> key}
    end
  end

  @doc """
  The line protocol of the measurements the cases read: `~m1` and `~m2` hold
  points from 2023 only, `~m3` to `~m7` and `~mw` points written without a
  time, so that they are in the last day (`~mt` holds one field of each type).
  """
  @spec fixture(%{binary() => binary()}) :: [binary()]
  def fixture(names) do
    %{"m1" => m1, "m2" => m2, "m3" => m3, "m4" => m4, "m5" => m5} = names
    %{"m6" => m6, "m7" => m7, "mw" => mw, "mt" => mt} = names

    [
      "#{m1},host=h1,region=east usage=1.5,n=1i 1700000000000000000",
      "#{m1},host=h2 usage=2.5,flag=true 1700000060000000000",
      ~s(#{m2},host=h1,dc=x s="str" 1700000000000000000),
      "#{m3},host=h1,region=east usage=1.5,n=1i",
      "#{m3},host=h2 usage=2.5,flag=true",
      ~s(#{m4},host=h1,dc=x s="str"),
      "#{m5},zone=z1 v=1",
      "#{m6},Host=h1 u=1",
      "#{m7},b=1,B=2,a=3,A=4 u=1",
      "#{mw}-hy,host=h1,region=r u=1",
      "#{mw}.dot,host=h1 u=1",
      "#{mw}\\ sp,host=h1 u=1",
      ~s(#{mt},t=1 f=1.5,i=1i,u=1u,s="x",b=true)
    ]
  end

  @doc "`SHOW MEASUREMENTS`: `WITH MEASUREMENT`, `WHERE`, `LIMIT`, `OFFSET`, `ON`."
  @spec measurements() :: [{binary(), [map()] | {:error, pos_integer(), binary()}}]
  def measurements do
    [
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/",
       [
         %{"iox::measurement" => "measurements", "name" => "~m1"},
         %{"iox::measurement" => "measurements", "name" => "~m2"},
         %{"iox::measurement" => "measurements", "name" => "~m3"},
         %{"iox::measurement" => "measurements", "name" => "~m4"},
         %{"iox::measurement" => "measurements", "name" => "~m5"},
         %{"iox::measurement" => "measurements", "name" => "~m6"},
         %{"iox::measurement" => "measurements", "name" => "~m7"},
         %{"iox::measurement" => "measurements", "name" => "~mt"},
         %{"iox::measurement" => "measurements", "name" => "~mw sp"},
         %{"iox::measurement" => "measurements", "name" => "~mw-hy"},
         %{"iox::measurement" => "measurements", "name" => "~mw.dot"}
       ]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ LIMIT 2",
       [
         %{"iox::measurement" => "measurements", "name" => "~m1"},
         %{"iox::measurement" => "measurements", "name" => "~m2"}
       ]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ LIMIT 2 OFFSET 1",
       [
         %{"iox::measurement" => "measurements", "name" => "~m2"},
         %{"iox::measurement" => "measurements", "name" => "~m3"}
       ]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ OFFSET 1",
       [
         %{"iox::measurement" => "measurements", "name" => "~m2"},
         %{"iox::measurement" => "measurements", "name" => "~m3"},
         %{"iox::measurement" => "measurements", "name" => "~m4"},
         %{"iox::measurement" => "measurements", "name" => "~m5"},
         %{"iox::measurement" => "measurements", "name" => "~m6"},
         %{"iox::measurement" => "measurements", "name" => "~m7"},
         %{"iox::measurement" => "measurements", "name" => "~mt"},
         %{"iox::measurement" => "measurements", "name" => "~mw sp"},
         %{"iox::measurement" => "measurements", "name" => "~mw-hy"},
         %{"iox::measurement" => "measurements", "name" => "~mw.dot"}
       ]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ OFFSET 100", []},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ LIMIT 0", []},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ LIMIT 1;",
       [%{"iox::measurement" => "measurements", "name" => "~m1"}]},
      {"show measurements with measurement =~ /^~p/ limit 1 offset 1",
       [%{"iox::measurement" => "measurements", "name" => "~m2"}]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT=~/^~p/",
       [
         %{"iox::measurement" => "measurements", "name" => "~m1"},
         %{"iox::measurement" => "measurements", "name" => "~m2"},
         %{"iox::measurement" => "measurements", "name" => "~m3"},
         %{"iox::measurement" => "measurements", "name" => "~m4"},
         %{"iox::measurement" => "measurements", "name" => "~m5"},
         %{"iox::measurement" => "measurements", "name" => "~m6"},
         %{"iox::measurement" => "measurements", "name" => "~m7"},
         %{"iox::measurement" => "measurements", "name" => "~mt"},
         %{"iox::measurement" => "measurements", "name" => "~mw sp"},
         %{"iox::measurement" => "measurements", "name" => "~mw-hy"},
         %{"iox::measurement" => "measurements", "name" => "~mw.dot"}
       ]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ ;;",
       [
         %{"iox::measurement" => "measurements", "name" => "~m1"},
         %{"iox::measurement" => "measurements", "name" => "~m2"},
         %{"iox::measurement" => "measurements", "name" => "~m3"},
         %{"iox::measurement" => "measurements", "name" => "~m4"},
         %{"iox::measurement" => "measurements", "name" => "~m5"},
         %{"iox::measurement" => "measurements", "name" => "~m6"},
         %{"iox::measurement" => "measurements", "name" => "~m7"},
         %{"iox::measurement" => "measurements", "name" => "~mt"},
         %{"iox::measurement" => "measurements", "name" => "~mw sp"},
         %{"iox::measurement" => "measurements", "name" => "~mw-hy"},
         %{"iox::measurement" => "measurements", "name" => "~mw.dot"}
       ]},
      {"  SHOW   MEASUREMENTS   WITH   MEASUREMENT   =~   /^~p/  ",
       [
         %{"iox::measurement" => "measurements", "name" => "~m1"},
         %{"iox::measurement" => "measurements", "name" => "~m2"},
         %{"iox::measurement" => "measurements", "name" => "~m3"},
         %{"iox::measurement" => "measurements", "name" => "~m4"},
         %{"iox::measurement" => "measurements", "name" => "~m5"},
         %{"iox::measurement" => "measurements", "name" => "~m6"},
         %{"iox::measurement" => "measurements", "name" => "~m7"},
         %{"iox::measurement" => "measurements", "name" => "~mt"},
         %{"iox::measurement" => "measurements", "name" => "~mw sp"},
         %{"iox::measurement" => "measurements", "name" => "~mw-hy"},
         %{"iox::measurement" => "measurements", "name" => "~mw.dot"}
       ]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p_m[12]$/",
       [
         %{"iox::measurement" => "measurements", "name" => "~m1"},
         %{"iox::measurement" => "measurements", "name" => "~m2"}
       ]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p_m[1-3]$/",
       [
         %{"iox::measurement" => "measurements", "name" => "~m1"},
         %{"iox::measurement" => "measurements", "name" => "~m2"},
         %{"iox::measurement" => "measurements", "name" => "~m3"}
       ]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p_M1$/", []},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /(?i)^~p_M1$/",
       [%{"iox::measurement" => "measurements", "name" => "~m1"}]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT = \"~m1\"",
       [%{"iox::measurement" => "measurements", "name" => "~m1"}]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT = ~m1",
       [%{"iox::measurement" => "measurements", "name" => "~m1"}]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT = \"~m1\" LIMIT 5",
       [%{"iox::measurement" => "measurements", "name" => "~m1"}]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT = \"~m1\" LIMIT 1 OFFSET 1", []},
      {"SHOW MEASUREMENTS WITH MEASUREMENT = \"nope\"", []},
      {"SHOW MEASUREMENTS WITH MEASUREMENT = \"~mw-hy\"",
       [%{"iox::measurement" => "measurements", "name" => "~mw-hy"}]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT = \"~mw.dot\"",
       [%{"iox::measurement" => "measurements", "name" => "~mw.dot"}]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT = \"~mw sp\"",
       [%{"iox::measurement" => "measurements", "name" => "~mw sp"}]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT = \"~mw-hy\" WHERE host = 'h1'",
       [%{"iox::measurement" => "measurements", "name" => "~mw-hy"}]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ WHERE host = 'h1'",
       [
         %{"iox::measurement" => "measurements", "name" => "~m3"},
         %{"iox::measurement" => "measurements", "name" => "~m4"},
         %{"iox::measurement" => "measurements", "name" => "~mw sp"},
         %{"iox::measurement" => "measurements", "name" => "~mw-hy"},
         %{"iox::measurement" => "measurements", "name" => "~mw.dot"}
       ]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ WHERE host = 'h2'",
       [%{"iox::measurement" => "measurements", "name" => "~m3"}]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ WHERE host = 'h1' LIMIT 1",
       [%{"iox::measurement" => "measurements", "name" => "~m3"}]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ WHERE host = 'h1' LIMIT 1 OFFSET 1",
       [%{"iox::measurement" => "measurements", "name" => "~m4"}]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ WHERE host = 'h1' OFFSET 1", []},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ WHERE \"host\" = 'h1'",
       [
         %{"iox::measurement" => "measurements", "name" => "~m3"},
         %{"iox::measurement" => "measurements", "name" => "~m4"},
         %{"iox::measurement" => "measurements", "name" => "~mw sp"},
         %{"iox::measurement" => "measurements", "name" => "~mw-hy"},
         %{"iox::measurement" => "measurements", "name" => "~mw.dot"}
       ]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ WHERE host != 'h1'",
       [%{"iox::measurement" => "measurements", "name" => "~m3"}]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ WHERE host =~ /h/",
       [
         %{"iox::measurement" => "measurements", "name" => "~m3"},
         %{"iox::measurement" => "measurements", "name" => "~m4"},
         %{"iox::measurement" => "measurements", "name" => "~mw sp"},
         %{"iox::measurement" => "measurements", "name" => "~mw-hy"},
         %{"iox::measurement" => "measurements", "name" => "~mw.dot"}
       ]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ WHERE host !~ /h/", []},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ WHERE host = \"h1\"", []},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ WHERE Host = 'h1'",
       [%{"iox::measurement" => "measurements", "name" => "~m6"}]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ WHERE region = 'east'",
       [%{"iox::measurement" => "measurements", "name" => "~m3"}]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ WHERE host = 'h1' AND region = 'east'",
       [%{"iox::measurement" => "measurements", "name" => "~m3"}]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ WHERE usage > 1",
       [%{"iox::measurement" => "measurements", "name" => "~m3"}]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ WHERE usage > 2 AND n = 1", []},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ WHERE flag = true",
       [%{"iox::measurement" => "measurements", "name" => "~m3"}]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT = \"~mt\" WHERE u > 0",
       [%{"iox::measurement" => "measurements", "name" => "~mt"}]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT = \"~mt\" WHERE u > 1", []},
      {"SHOW MEASUREMENTS WITH MEASUREMENT = \"~mt\" WHERE s = 'x'",
       [%{"iox::measurement" => "measurements", "name" => "~mt"}]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT = \"~mt\" WHERE b = true AND i = 1 AND f = 1.5",
       [%{"iox::measurement" => "measurements", "name" => "~mt"}]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ WHERE host > 1", []},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ WHERE usage = 'x'", []},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ WHERE nope = 'x'", []},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ WHERE nope != 'x'", []},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ WHERE time > 0",
       [
         %{"iox::measurement" => "measurements", "name" => "~m1"},
         %{"iox::measurement" => "measurements", "name" => "~m2"},
         %{"iox::measurement" => "measurements", "name" => "~m3"},
         %{"iox::measurement" => "measurements", "name" => "~m4"},
         %{"iox::measurement" => "measurements", "name" => "~m5"},
         %{"iox::measurement" => "measurements", "name" => "~m6"},
         %{"iox::measurement" => "measurements", "name" => "~m7"},
         %{"iox::measurement" => "measurements", "name" => "~mt"},
         %{"iox::measurement" => "measurements", "name" => "~mw sp"},
         %{"iox::measurement" => "measurements", "name" => "~mw-hy"},
         %{"iox::measurement" => "measurements", "name" => "~mw.dot"}
       ]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ WHERE time > 0 AND host = 'h1'",
       [
         %{"iox::measurement" => "measurements", "name" => "~m1"},
         %{"iox::measurement" => "measurements", "name" => "~m2"},
         %{"iox::measurement" => "measurements", "name" => "~m3"},
         %{"iox::measurement" => "measurements", "name" => "~m4"},
         %{"iox::measurement" => "measurements", "name" => "~mw sp"},
         %{"iox::measurement" => "measurements", "name" => "~mw-hy"},
         %{"iox::measurement" => "measurements", "name" => "~mw.dot"}
       ]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ WHERE host = 'h1' AND time > 0",
       [
         %{"iox::measurement" => "measurements", "name" => "~m1"},
         %{"iox::measurement" => "measurements", "name" => "~m2"},
         %{"iox::measurement" => "measurements", "name" => "~m3"},
         %{"iox::measurement" => "measurements", "name" => "~m4"},
         %{"iox::measurement" => "measurements", "name" => "~mw sp"},
         %{"iox::measurement" => "measurements", "name" => "~mw-hy"},
         %{"iox::measurement" => "measurements", "name" => "~mw.dot"}
       ]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ WHERE time > now() - 1h AND host = 'h1'",
       [
         %{"iox::measurement" => "measurements", "name" => "~m3"},
         %{"iox::measurement" => "measurements", "name" => "~m4"},
         %{"iox::measurement" => "measurements", "name" => "~mw sp"},
         %{"iox::measurement" => "measurements", "name" => "~mw-hy"},
         %{"iox::measurement" => "measurements", "name" => "~mw.dot"}
       ]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ WHERE time < now() - 1d",
       [
         %{"iox::measurement" => "measurements", "name" => "~m1"},
         %{"iox::measurement" => "measurements", "name" => "~m2"}
       ]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ WHERE time > '2020-01-01T00:00:00Z'",
       [
         %{"iox::measurement" => "measurements", "name" => "~m1"},
         %{"iox::measurement" => "measurements", "name" => "~m2"},
         %{"iox::measurement" => "measurements", "name" => "~m3"},
         %{"iox::measurement" => "measurements", "name" => "~m4"},
         %{"iox::measurement" => "measurements", "name" => "~m5"},
         %{"iox::measurement" => "measurements", "name" => "~m6"},
         %{"iox::measurement" => "measurements", "name" => "~m7"},
         %{"iox::measurement" => "measurements", "name" => "~mt"},
         %{"iox::measurement" => "measurements", "name" => "~mw sp"},
         %{"iox::measurement" => "measurements", "name" => "~mw-hy"},
         %{"iox::measurement" => "measurements", "name" => "~mw.dot"}
       ]},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /^~p/ WHERE time < '2020-01-01T00:00:00Z'", []},
      {"SHOW MEASUREMENTS ON ~db WITH MEASUREMENT = \"~m1\"",
       [%{"iox::measurement" => "measurements", "name" => "~m1"}]},
      {"SHOW MEASUREMENTS ON \"~db\" WITH MEASUREMENT = \"~m1\"",
       [%{"iox::measurement" => "measurements", "name" => "~m1"}]},
      {"SHOW MEASUREMENTS ON ~db.autogen WITH MEASUREMENT = \"~m1\"",
       [%{"iox::measurement" => "measurements", "name" => "~m1"}]},
      {"SHOW MEASUREMENTS ON ~db WITH MEASUREMENT =~ /^~p/ LIMIT 2",
       [
         %{"iox::measurement" => "measurements", "name" => "~m1"},
         %{"iox::measurement" => "measurements", "name" => "~m2"}
       ]},
      {"SHOW MEASUREMENTS ON nope WITH MEASUREMENT = \"~m1\"",
       {:error, 400,
        "provided a database in both the parameters (~db) and query string (nope) that do not match, if providing a query that specifies the database, you can omit the 'database' parameter from your request"}},
      {"SHOW MEASUREMENTS ON ~db.nope WITH MEASUREMENT = \"~m1\"",
       {:error, 400,
        "provided a database in both the parameters (~db) and query string (~db/nope) that do not match, if providing a query that specifies the database, you can omit the 'database' parameter from your request"}},
      {"SHOW MEASUREMENTS ON * WITH MEASUREMENT = \"~m1\"",
       {:error, 400, "error in InfluxQL statement: can only perform queries on a single database"}}
    ]
  end

  @doc "`SHOW TAG KEYS`: `FROM` names and expressions, `WHERE`, `LIMIT`, `OFFSET`, `ON`."
  @spec tag_keys() :: [{binary(), [map()] | {:error, pos_integer(), binary()}}]
  def tag_keys do
    [
      {"SHOW TAG KEYS FROM \"~m1\"",
       [
         %{"iox::measurement" => "~m1", "tagKey" => "host"},
         %{"iox::measurement" => "~m1", "tagKey" => "region"}
       ]},
      {"SHOW TAG KEYS FROM \"~m3\"",
       [
         %{"iox::measurement" => "~m3", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "region"}
       ]},
      {"SHOW TAG KEYS FROM ~m3",
       [
         %{"iox::measurement" => "~m3", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "region"}
       ]},
      {"SHOW TAG KEYS FROM \"~m3\", \"~m4\"",
       [
         %{"iox::measurement" => "~m3", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "region"},
         %{"iox::measurement" => "~m4", "tagKey" => "dc"},
         %{"iox::measurement" => "~m4", "tagKey" => "host"}
       ]},
      {"SHOW TAG KEYS FROM \"~m4\", \"~m3\"",
       [
         %{"iox::measurement" => "~m3", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "region"},
         %{"iox::measurement" => "~m4", "tagKey" => "dc"},
         %{"iox::measurement" => "~m4", "tagKey" => "host"}
       ]},
      {"SHOW TAG KEYS FROM \"~m3\",\"~m3\"",
       [
         %{"iox::measurement" => "~m3", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "region"}
       ]},
      {"SHOW TAG KEYS FROM ~m3,~m4",
       [
         %{"iox::measurement" => "~m3", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "region"},
         %{"iox::measurement" => "~m4", "tagKey" => "dc"},
         %{"iox::measurement" => "~m4", "tagKey" => "host"}
       ]},
      {"SHOW TAG KEYS FROM \"~m3\" , \"~m4\"",
       [
         %{"iox::measurement" => "~m3", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "region"},
         %{"iox::measurement" => "~m4", "tagKey" => "dc"},
         %{"iox::measurement" => "~m4", "tagKey" => "host"}
       ]},
      {"SHOW TAG KEYS FROM /^~p_m[34]$/",
       [
         %{"iox::measurement" => "~m3", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "region"},
         %{"iox::measurement" => "~m4", "tagKey" => "dc"},
         %{"iox::measurement" => "~m4", "tagKey" => "host"}
       ]},
      {"SHOW TAG KEYS FROM /^~p_m[34]$/, \"~m5\"",
       [
         %{"iox::measurement" => "~m3", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "region"},
         %{"iox::measurement" => "~m4", "tagKey" => "dc"},
         %{"iox::measurement" => "~m4", "tagKey" => "host"},
         %{"iox::measurement" => "~m5", "tagKey" => "zone"}
       ]},
      {"SHOW TAG KEYS FROM \"~m3\", /^~p_m4$/",
       [
         %{"iox::measurement" => "~m3", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "region"},
         %{"iox::measurement" => "~m4", "tagKey" => "dc"},
         %{"iox::measurement" => "~m4", "tagKey" => "host"}
       ]},
      {"SHOW TAG KEYS FROM /^~p_m[34]$/,/^~p_m5$/",
       [
         %{"iox::measurement" => "~m3", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "region"},
         %{"iox::measurement" => "~m4", "tagKey" => "dc"},
         %{"iox::measurement" => "~m4", "tagKey" => "host"},
         %{"iox::measurement" => "~m5", "tagKey" => "zone"}
       ]},
      {"SHOW TAG KEYS FROM /^~p_M3$/", []},
      {"SHOW TAG KEYS FROM /(?i)^~p_M3$/",
       [
         %{"iox::measurement" => "~m3", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "region"}
       ]},
      {"SHOW TAG KEYS FROM /^~p_m3\\_/", []},
      {"SHOW TAG KEYS FROM /^~p/",
       [
         %{"iox::measurement" => "~m1", "tagKey" => "host"},
         %{"iox::measurement" => "~m1", "tagKey" => "region"},
         %{"iox::measurement" => "~m2", "tagKey" => "dc"},
         %{"iox::measurement" => "~m2", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "region"},
         %{"iox::measurement" => "~m4", "tagKey" => "dc"},
         %{"iox::measurement" => "~m4", "tagKey" => "host"},
         %{"iox::measurement" => "~m5", "tagKey" => "zone"},
         %{"iox::measurement" => "~m6", "tagKey" => "Host"},
         %{"iox::measurement" => "~m7", "tagKey" => "A"},
         %{"iox::measurement" => "~m7", "tagKey" => "B"},
         %{"iox::measurement" => "~m7", "tagKey" => "a"},
         %{"iox::measurement" => "~m7", "tagKey" => "b"},
         %{"iox::measurement" => "~mt", "tagKey" => "t"},
         %{"iox::measurement" => "~mw sp", "tagKey" => "host"},
         %{"iox::measurement" => "~mw-hy", "tagKey" => "host"},
         %{"iox::measurement" => "~mw-hy", "tagKey" => "region"},
         %{"iox::measurement" => "~mw.dot", "tagKey" => "host"}
       ]},
      {"SHOW TAG KEYS FROM /^~p/ LIMIT 1",
       [
         %{"iox::measurement" => "~m1", "tagKey" => "host"},
         %{"iox::measurement" => "~m2", "tagKey" => "dc"},
         %{"iox::measurement" => "~m3", "tagKey" => "host"},
         %{"iox::measurement" => "~m4", "tagKey" => "dc"},
         %{"iox::measurement" => "~m5", "tagKey" => "zone"},
         %{"iox::measurement" => "~m6", "tagKey" => "Host"},
         %{"iox::measurement" => "~m7", "tagKey" => "A"},
         %{"iox::measurement" => "~mt", "tagKey" => "t"},
         %{"iox::measurement" => "~mw sp", "tagKey" => "host"},
         %{"iox::measurement" => "~mw-hy", "tagKey" => "host"},
         %{"iox::measurement" => "~mw.dot", "tagKey" => "host"}
       ]},
      {"SHOW TAG KEYS FROM /^~p/ LIMIT 2 OFFSET 1",
       [
         %{"iox::measurement" => "~m1", "tagKey" => "region"},
         %{"iox::measurement" => "~m2", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "region"},
         %{"iox::measurement" => "~m4", "tagKey" => "host"},
         %{"iox::measurement" => "~m7", "tagKey" => "B"},
         %{"iox::measurement" => "~m7", "tagKey" => "a"},
         %{"iox::measurement" => "~mw-hy", "tagKey" => "region"}
       ]},
      {"SHOW TAG KEYS FROM /^~p/ OFFSET 1",
       [
         %{"iox::measurement" => "~m1", "tagKey" => "region"},
         %{"iox::measurement" => "~m2", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "region"},
         %{"iox::measurement" => "~m4", "tagKey" => "host"},
         %{"iox::measurement" => "~m7", "tagKey" => "B"},
         %{"iox::measurement" => "~m7", "tagKey" => "a"},
         %{"iox::measurement" => "~m7", "tagKey" => "b"},
         %{"iox::measurement" => "~mw-hy", "tagKey" => "region"}
       ]},
      {"SHOW TAG KEYS FROM /^~p/ OFFSET 3", [%{"iox::measurement" => "~m7", "tagKey" => "b"}]},
      {"SHOW TAG KEYS FROM \"~m3\" LIMIT 1",
       [%{"iox::measurement" => "~m3", "tagKey" => "host"}]},
      {"SHOW TAG KEYS FROM \"~m3\" LIMIT 1 OFFSET 1",
       [%{"iox::measurement" => "~m3", "tagKey" => "region"}]},
      {"SHOW TAG KEYS FROM \"~m3\" LIMIT 0", []},
      {"SHOW TAG KEYS FROM \"~m3\" OFFSET 2", []},
      {"SHOW TAG KEYS FROM \"~m3\" LIMIT 18446744073709551615",
       [
         %{"iox::measurement" => "~m3", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "region"}
       ]},
      {"SHOW TAG KEYS FROM \"~m3\" OFFSET 18446744073709551615", []},
      {"SHOW TAG KEYS FROM \"~m3\" LIMIT 9223372036854775808",
       [
         %{"iox::measurement" => "~m3", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "region"}
       ]},
      {"SHOW TAG KEYS FROM \"~m3\" LIMIT 9223372036854775808 OFFSET 1",
       [%{"iox::measurement" => "~m3", "tagKey" => "region"}]},
      {"SHOW TAG KEYS FROM \"nope\"", []},
      {"SHOW TAG KEYS FROM \"nope\" LIMIT 1 OFFSET 9223372036854775808", []},
      {"SHOW TAG KEYS FROM \"~m3\", \"nope\"",
       [
         %{"iox::measurement" => "~m3", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "region"}
       ]},
      {"SHOW TAG KEYS FROM \"\"", []},
      {"SHOW TAG KEYS FROM \"~m5\"", [%{"iox::measurement" => "~m5", "tagKey" => "zone"}]},
      {"SHOW TAG KEYS FROM \"~m6\"", [%{"iox::measurement" => "~m6", "tagKey" => "Host"}]},
      {"SHOW TAG KEYS FROM \"~m7\"",
       [
         %{"iox::measurement" => "~m7", "tagKey" => "A"},
         %{"iox::measurement" => "~m7", "tagKey" => "B"},
         %{"iox::measurement" => "~m7", "tagKey" => "a"},
         %{"iox::measurement" => "~m7", "tagKey" => "b"}
       ]},
      {"SHOW TAG KEYS FROM \"~mt\"", [%{"iox::measurement" => "~mt", "tagKey" => "t"}]},
      {"SHOW TAG KEYS FROM \"~mw-hy\"",
       [
         %{"iox::measurement" => "~mw-hy", "tagKey" => "host"},
         %{"iox::measurement" => "~mw-hy", "tagKey" => "region"}
       ]},
      {"SHOW TAG KEYS FROM \"~mw.dot\"",
       [%{"iox::measurement" => "~mw.dot", "tagKey" => "host"}]},
      {"SHOW TAG KEYS FROM \"~mw sp\"", [%{"iox::measurement" => "~mw sp", "tagKey" => "host"}]},
      {"SHOW TAG KEYS FROM \"~m3\";",
       [
         %{"iox::measurement" => "~m3", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "region"}
       ]},
      {"show tag keys from \"~m3\"",
       [
         %{"iox::measurement" => "~m3", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "region"}
       ]},
      {"SHOW TAG KEYS FROM \"~M3\"", []},
      {"SHOW TAG KEYS FROM \"~m3\\\"\"", []},
      {"SHOW TAG KEYS FROM \"a\\nb\"", []},
      {"SHOW TAG KEYS FROM \"a\\\\nb\"", []},
      {"SHOW TAG KEYS FROM time", []},
      {"SHOW TAG KEYS FROM \"limit\"", []},
      {"SHOW TAG KEYS FROM _a", []},
      {"SHOW TAG KEYS ON ~db FROM \"~m3\"",
       [
         %{"iox::measurement" => "~m3", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "region"}
       ]},
      {"SHOW TAG KEYS ON \"~db\" FROM \"~m3\"",
       [
         %{"iox::measurement" => "~m3", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "region"}
       ]},
      {"SHOW TAG KEYS ON nope FROM \"~m3\"",
       {:error, 400,
        "provided a database in both the parameters (~db) and query string (nope) that do not match, if providing a query that specifies the database, you can omit the 'database' parameter from your request"}},
      {"SHOW TAG KEYS FROM /^~p/ WHERE host = 'h1'",
       [
         %{"iox::measurement" => "~m3", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "region"},
         %{"iox::measurement" => "~m4", "tagKey" => "dc"},
         %{"iox::measurement" => "~m4", "tagKey" => "host"},
         %{"iox::measurement" => "~mw sp", "tagKey" => "host"},
         %{"iox::measurement" => "~mw-hy", "tagKey" => "host"},
         %{"iox::measurement" => "~mw-hy", "tagKey" => "region"},
         %{"iox::measurement" => "~mw.dot", "tagKey" => "host"}
       ]},
      {"SHOW TAG KEYS FROM /^~p/ WHERE time > 0 AND host = 'h1'",
       [
         %{"iox::measurement" => "~m1", "tagKey" => "host"},
         %{"iox::measurement" => "~m1", "tagKey" => "region"},
         %{"iox::measurement" => "~m2", "tagKey" => "dc"},
         %{"iox::measurement" => "~m2", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "region"},
         %{"iox::measurement" => "~m4", "tagKey" => "dc"},
         %{"iox::measurement" => "~m4", "tagKey" => "host"},
         %{"iox::measurement" => "~mw sp", "tagKey" => "host"},
         %{"iox::measurement" => "~mw-hy", "tagKey" => "host"},
         %{"iox::measurement" => "~mw-hy", "tagKey" => "region"},
         %{"iox::measurement" => "~mw.dot", "tagKey" => "host"}
       ]},
      {"SHOW TAG KEYS FROM \"~m3\" WHERE host = 'h2'",
       [%{"iox::measurement" => "~m3", "tagKey" => "host"}]},
      {"SHOW TAG KEYS FROM \"~m3\" WHERE host = 'h1'",
       [
         %{"iox::measurement" => "~m3", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "region"}
       ]},
      {"SHOW TAG KEYS FROM \"~m3\" WHERE usage > 1",
       [
         %{"iox::measurement" => "~m3", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "region"}
       ]},
      {"SHOW TAG KEYS FROM \"~m3\" WHERE host != 'h1'",
       [%{"iox::measurement" => "~m3", "tagKey" => "host"}]},
      {"SHOW TAG KEYS FROM \"~m3\" WHERE region = ''",
       [%{"iox::measurement" => "~m3", "tagKey" => "host"}]},
      {"SHOW TAG KEYS FROM \"~m3\" WHERE region != ''",
       [
         %{"iox::measurement" => "~m3", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "region"}
       ]},
      {"SHOW TAG KEYS FROM \"~m3\" WHERE host =~ /^h/ AND host !~ /2/",
       [
         %{"iox::measurement" => "~m3", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "region"}
       ]},
      {"SHOW TAG KEYS FROM \"~m3\" WHERE (host = 'h1' OR host = 'h2') AND region = 'east'",
       [
         %{"iox::measurement" => "~m3", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "region"}
       ]},
      {"SHOW TAG KEYS FROM \"~m3\" WHERE nope = 'x'", []},
      {"SHOW TAG KEYS FROM \"~m3\" WHERE host > 1", []},
      {"SHOW TAG KEYS FROM \"~m3\" WHERE time > now() - 1h",
       [
         %{"iox::measurement" => "~m3", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "region"}
       ]},
      {"SHOW TAG KEYS FROM \"~m3\" WHERE time < now() - 1d", []},
      {"SHOW TAG KEYS FROM \"~m1\" WHERE host = 'h2'", []},
      {"SHOW TAG KEYS FROM \"~m1\" WHERE time > 0 AND host = 'h2'",
       [%{"iox::measurement" => "~m1", "tagKey" => "host"}]},
      {"SHOW TAG KEYS FROM \"~m1\" WHERE time > 0 AND region = 'east'",
       [
         %{"iox::measurement" => "~m1", "tagKey" => "host"},
         %{"iox::measurement" => "~m1", "tagKey" => "region"}
       ]},
      {"SHOW TAG KEYS FROM /^~p/ WHERE zone = 'z1'",
       [%{"iox::measurement" => "~m5", "tagKey" => "zone"}]},
      {"SHOW TAG KEYS FROM /^~p/ WHERE usage > 1",
       [
         %{"iox::measurement" => "~m3", "tagKey" => "host"},
         %{"iox::measurement" => "~m3", "tagKey" => "region"}
       ]},
      {"SHOW TAG KEYS FROM \"nope\" WHERE host = 'h1'", []},
      {"SHOW TAG KEYS FROM \"nope\" WHERE host = 'h1' LIMIT 1", []}
    ]
  end

  @doc "`SHOW FIELD KEYS`: `FROM` names and expressions, `LIMIT`, `OFFSET`, `ON`."
  @spec field_keys() :: [{binary(), [map()] | {:error, pos_integer(), binary()}}]
  def field_keys do
    [
      {"SHOW FIELD KEYS FROM \"~m3\"",
       [
         %{"fieldKey" => "flag", "fieldType" => "boolean", "iox::measurement" => "~m3"},
         %{"fieldKey" => "n", "fieldType" => "integer", "iox::measurement" => "~m3"},
         %{"fieldKey" => "usage", "fieldType" => "float", "iox::measurement" => "~m3"}
       ]},
      {"SHOW FIELD KEYS FROM \"~m3\", \"~m4\"",
       [
         %{"fieldKey" => "flag", "fieldType" => "boolean", "iox::measurement" => "~m3"},
         %{"fieldKey" => "n", "fieldType" => "integer", "iox::measurement" => "~m3"},
         %{"fieldKey" => "usage", "fieldType" => "float", "iox::measurement" => "~m3"},
         %{"fieldKey" => "s", "fieldType" => "string", "iox::measurement" => "~m4"}
       ]},
      {"SHOW FIELD KEYS FROM \"~m4\", \"~m3\"",
       [
         %{"fieldKey" => "flag", "fieldType" => "boolean", "iox::measurement" => "~m3"},
         %{"fieldKey" => "n", "fieldType" => "integer", "iox::measurement" => "~m3"},
         %{"fieldKey" => "usage", "fieldType" => "float", "iox::measurement" => "~m3"},
         %{"fieldKey" => "s", "fieldType" => "string", "iox::measurement" => "~m4"}
       ]},
      {"SHOW FIELD KEYS FROM /^~p_m[34]$/",
       [
         %{"fieldKey" => "flag", "fieldType" => "boolean", "iox::measurement" => "~m3"},
         %{"fieldKey" => "n", "fieldType" => "integer", "iox::measurement" => "~m3"},
         %{"fieldKey" => "usage", "fieldType" => "float", "iox::measurement" => "~m3"},
         %{"fieldKey" => "s", "fieldType" => "string", "iox::measurement" => "~m4"}
       ]},
      {"SHOW FIELD KEYS FROM /^~p_m[34]$/ LIMIT 2",
       [
         %{"fieldKey" => "flag", "fieldType" => "boolean", "iox::measurement" => "~m3"},
         %{"fieldKey" => "n", "fieldType" => "integer", "iox::measurement" => "~m3"},
         %{"fieldKey" => "s", "fieldType" => "string", "iox::measurement" => "~m4"}
       ]},
      {"SHOW FIELD KEYS FROM /^~p_m[34]$/ LIMIT 2 OFFSET 2",
       [%{"fieldKey" => "usage", "fieldType" => "float", "iox::measurement" => "~m3"}]},
      {"SHOW FIELD KEYS FROM /^~p_m[34]$/ OFFSET 1",
       [
         %{"fieldKey" => "n", "fieldType" => "integer", "iox::measurement" => "~m3"},
         %{"fieldKey" => "usage", "fieldType" => "float", "iox::measurement" => "~m3"}
       ]},
      {"SHOW FIELD KEYS FROM /^~p_m[34]$/ LIMIT 0", []},
      {"SHOW FIELD KEYS FROM \"~m3\" LIMIT 1 OFFSET 1",
       [%{"fieldKey" => "n", "fieldType" => "integer", "iox::measurement" => "~m3"}]},
      {"SHOW FIELD KEYS FROM \"~m3\" LIMIT 18446744073709551615",
       [
         %{"fieldKey" => "flag", "fieldType" => "boolean", "iox::measurement" => "~m3"},
         %{"fieldKey" => "n", "fieldType" => "integer", "iox::measurement" => "~m3"},
         %{"fieldKey" => "usage", "fieldType" => "float", "iox::measurement" => "~m3"}
       ]},
      {"SHOW FIELD KEYS FROM \"~m3\" OFFSET 9223372036854775808", []},
      {"SHOW FIELD KEYS FROM \"~m1\"",
       [
         %{"fieldKey" => "flag", "fieldType" => "boolean", "iox::measurement" => "~m1"},
         %{"fieldKey" => "n", "fieldType" => "integer", "iox::measurement" => "~m1"},
         %{"fieldKey" => "usage", "fieldType" => "float", "iox::measurement" => "~m1"}
       ]},
      {"SHOW FIELD KEYS FROM \"~m5\"",
       [%{"fieldKey" => "v", "fieldType" => "float", "iox::measurement" => "~m5"}]},
      {"SHOW FIELD KEYS FROM \"~mt\"",
       [
         %{"fieldKey" => "b", "fieldType" => "boolean", "iox::measurement" => "~mt"},
         %{"fieldKey" => "f", "fieldType" => "float", "iox::measurement" => "~mt"},
         %{"fieldKey" => "i", "fieldType" => "integer", "iox::measurement" => "~mt"},
         %{"fieldKey" => "s", "fieldType" => "string", "iox::measurement" => "~mt"},
         %{"fieldKey" => "u", "fieldType" => "unsigned", "iox::measurement" => "~mt"}
       ]},
      {"SHOW FIELD KEYS FROM \"~mt\" LIMIT 2 OFFSET 1",
       [
         %{"fieldKey" => "f", "fieldType" => "float", "iox::measurement" => "~mt"},
         %{"fieldKey" => "i", "fieldType" => "integer", "iox::measurement" => "~mt"}
       ]},
      {"SHOW FIELD KEYS FROM \"~m7\"",
       [%{"fieldKey" => "u", "fieldType" => "float", "iox::measurement" => "~m7"}]},
      {"SHOW FIELD KEYS FROM /^~p/",
       [
         %{"fieldKey" => "flag", "fieldType" => "boolean", "iox::measurement" => "~m1"},
         %{"fieldKey" => "n", "fieldType" => "integer", "iox::measurement" => "~m1"},
         %{"fieldKey" => "usage", "fieldType" => "float", "iox::measurement" => "~m1"},
         %{"fieldKey" => "s", "fieldType" => "string", "iox::measurement" => "~m2"},
         %{"fieldKey" => "flag", "fieldType" => "boolean", "iox::measurement" => "~m3"},
         %{"fieldKey" => "n", "fieldType" => "integer", "iox::measurement" => "~m3"},
         %{"fieldKey" => "usage", "fieldType" => "float", "iox::measurement" => "~m3"},
         %{"fieldKey" => "s", "fieldType" => "string", "iox::measurement" => "~m4"},
         %{"fieldKey" => "v", "fieldType" => "float", "iox::measurement" => "~m5"},
         %{"fieldKey" => "u", "fieldType" => "float", "iox::measurement" => "~m6"},
         %{"fieldKey" => "u", "fieldType" => "float", "iox::measurement" => "~m7"},
         %{"fieldKey" => "b", "fieldType" => "boolean", "iox::measurement" => "~mt"},
         %{"fieldKey" => "f", "fieldType" => "float", "iox::measurement" => "~mt"},
         %{"fieldKey" => "i", "fieldType" => "integer", "iox::measurement" => "~mt"},
         %{"fieldKey" => "s", "fieldType" => "string", "iox::measurement" => "~mt"},
         %{"fieldKey" => "u", "fieldType" => "unsigned", "iox::measurement" => "~mt"},
         %{"fieldKey" => "u", "fieldType" => "float", "iox::measurement" => "~mw sp"},
         %{"fieldKey" => "u", "fieldType" => "float", "iox::measurement" => "~mw-hy"},
         %{"fieldKey" => "u", "fieldType" => "float", "iox::measurement" => "~mw.dot"}
       ]},
      {"SHOW FIELD KEYS FROM \"nope\"", []},
      {"SHOW FIELD KEYS FROM \"nope\" LIMIT 1 OFFSET 9223372036854775808", []},
      {"SHOW FIELD KEYS ON ~db FROM \"~m3\"",
       [
         %{"fieldKey" => "flag", "fieldType" => "boolean", "iox::measurement" => "~m3"},
         %{"fieldKey" => "n", "fieldType" => "integer", "iox::measurement" => "~m3"},
         %{"fieldKey" => "usage", "fieldType" => "float", "iox::measurement" => "~m3"}
       ]},
      {"SHOW FIELD KEYS ON nope FROM \"~m3\"",
       {:error, 400,
        "provided a database in both the parameters (~db) and query string (nope) that do not match, if providing a query that specifies the database, you can omit the 'database' parameter from your request"}},
      {"SHOW FIELD KEYS FROM \"~m3\";",
       [
         %{"fieldKey" => "flag", "fieldType" => "boolean", "iox::measurement" => "~m3"},
         %{"fieldKey" => "n", "fieldType" => "integer", "iox::measurement" => "~m3"},
         %{"fieldKey" => "usage", "fieldType" => "float", "iox::measurement" => "~m3"}
       ]},
      {"show field keys from \"~m3\" limit 1",
       [%{"fieldKey" => "flag", "fieldType" => "boolean", "iox::measurement" => "~m3"}]}
    ]
  end

  @doc "`SHOW TAG VALUES`: the `WITH KEY` forms, `WHERE`, `LIMIT`, `OFFSET`, `ON`."
  @spec tag_values() :: [{binary(), [map()] | {:error, pos_integer(), binary()}}]
  def tag_values do
    [
      {"SHOW TAG VALUES FROM \"~m3\" WITH KEY = host",
       [
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h1"},
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h2"}
       ]},
      {"SHOW TAG VALUES FROM \"~m3\" WITH KEY = \"host\"",
       [
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h1"},
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h2"}
       ]},
      {"SHOW TAG VALUES FROM \"~m3\" WITH KEY=host",
       [
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h1"},
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h2"}
       ]},
      {"SHOW TAG VALUES FROM \"~m3\" WITH   KEY   =   host   WHERE   time > 0",
       [
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h1"},
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h2"}
       ]},
      {"SHOW TAG VALUES FROM \"~m3\" WITH KEY != host",
       [
         %{"iox::measurement" => "~m3", "key" => "region", "value" => "east"},
         %{"iox::measurement" => "~m3", "key" => "region"}
       ]},
      {"SHOW TAG VALUES FROM \"~m3\" WITH KEY =~ /./",
       [
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h1"},
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h2"},
         %{"iox::measurement" => "~m3", "key" => "region", "value" => "east"},
         %{"iox::measurement" => "~m3", "key" => "region"}
       ]},
      {"SHOW TAG VALUES FROM \"~m3\" WITH KEY =~ /^h/",
       [
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h1"},
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h2"}
       ]},
      {"SHOW TAG VALUES FROM \"~m3\" WITH KEY !~ /^h/",
       [
         %{"iox::measurement" => "~m3", "key" => "region", "value" => "east"},
         %{"iox::measurement" => "~m3", "key" => "region"}
       ]},
      {"SHOW TAG VALUES FROM \"~m3\" WITH KEY IN (host, region)",
       [
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h1"},
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h2"},
         %{"iox::measurement" => "~m3", "key" => "region", "value" => "east"},
         %{"iox::measurement" => "~m3", "key" => "region"}
       ]},
      {"SHOW TAG VALUES FROM \"~m3\" WITH KEY IN (host,region)",
       [
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h1"},
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h2"},
         %{"iox::measurement" => "~m3", "key" => "region", "value" => "east"},
         %{"iox::measurement" => "~m3", "key" => "region"}
       ]},
      {"SHOW TAG VALUES FROM \"~m3\" WITH KEY IN (host, \"region\")",
       [
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h1"},
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h2"},
         %{"iox::measurement" => "~m3", "key" => "region", "value" => "east"},
         %{"iox::measurement" => "~m3", "key" => "region"}
       ]},
      {"SHOW TAG VALUES FROM \"~m3\" WITH KEY = nope", []},
      {"SHOW TAG VALUES FROM \"~m3\" WITH KEY = usage", []},
      {"SHOW TAG VALUES FROM \"nope\" WITH KEY = host", []},
      {"SHOW TAG VALUES FROM \"~m1\" WITH KEY = host", []},
      {"SHOW TAG VALUES FROM \"~m1\" WITH KEY = host WHERE time > 0",
       [
         %{"iox::measurement" => "~m1", "key" => "host", "value" => "h1"},
         %{"iox::measurement" => "~m1", "key" => "host", "value" => "h2"}
       ]},
      {"SHOW TAG VALUES FROM \"~m1\" WITH KEY IN (host, region) WHERE time > 0",
       [
         %{"iox::measurement" => "~m1", "key" => "host", "value" => "h1"},
         %{"iox::measurement" => "~m1", "key" => "host", "value" => "h2"},
         %{"iox::measurement" => "~m1", "key" => "region", "value" => "east"},
         %{"iox::measurement" => "~m1", "key" => "region"}
       ]},
      {"SHOW TAG VALUES FROM \"~m1\" WITH KEY = host WHERE time > 0 AND host = 'h2'",
       [%{"iox::measurement" => "~m1", "key" => "host", "value" => "h2"}]},
      {"SHOW TAG VALUES FROM \"~m1\" WITH KEY = host WHERE host = 'h2' AND time > 0",
       [%{"iox::measurement" => "~m1", "key" => "host", "value" => "h2"}]},
      {"SHOW TAG VALUES FROM \"~m1\" WITH KEY = host WHERE time < 0", []},
      {"SHOW TAG VALUES FROM /^~p_m[34]$/ WITH KEY = host",
       [
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h1"},
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h2"},
         %{"iox::measurement" => "~m4", "key" => "host", "value" => "h1"}
       ]},
      {"SHOW TAG VALUES FROM /^~p_m[345]$/ WITH KEY IN (host, region, dc, zone)",
       [
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h1"},
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h2"},
         %{"iox::measurement" => "~m3", "key" => "region", "value" => "east"},
         %{"iox::measurement" => "~m3", "key" => "region"},
         %{"iox::measurement" => "~m4", "key" => "dc", "value" => "x"},
         %{"iox::measurement" => "~m4", "key" => "host", "value" => "h1"},
         %{"iox::measurement" => "~m5", "key" => "zone", "value" => "z1"}
       ]},
      {"SHOW TAG VALUES FROM /^~p_m[345]$/ WITH KEY =~ /./",
       [
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h1"},
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h2"},
         %{"iox::measurement" => "~m3", "key" => "region", "value" => "east"},
         %{"iox::measurement" => "~m3", "key" => "region"},
         %{"iox::measurement" => "~m4", "key" => "dc", "value" => "x"},
         %{"iox::measurement" => "~m4", "key" => "host", "value" => "h1"},
         %{"iox::measurement" => "~m5", "key" => "zone", "value" => "z1"}
       ]},
      {"SHOW TAG VALUES FROM /^~p_m[34]$/ WITH KEY = host WHERE host = 'h1'",
       [
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h1"},
         %{"iox::measurement" => "~m4", "key" => "host", "value" => "h1"}
       ]},
      {"SHOW TAG VALUES FROM \"~m3\" WITH KEY = host WHERE usage > 1",
       [
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h1"},
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h2"}
       ]},
      {"SHOW TAG VALUES FROM \"~m3\" WITH KEY = host WHERE host = 'h1' OR host = 'h2'",
       [
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h1"},
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h2"}
       ]},
      {"SHOW TAG VALUES FROM \"~m3\" WITH KEY = host WHERE host = 'h2' AND usage > 1",
       [%{"iox::measurement" => "~m3", "key" => "host", "value" => "h2"}]},
      {"SHOW TAG VALUES FROM \"~m3\" WITH KEY = region WHERE host = 'h1'",
       [%{"iox::measurement" => "~m3", "key" => "region", "value" => "east"}]},
      {"SHOW TAG VALUES FROM \"~m3\" WITH KEY = host WHERE nope = 'x'", []},
      {"SHOW TAG VALUES FROM \"~m6\" WITH KEY = Host",
       [%{"iox::measurement" => "~m6", "key" => "Host", "value" => "h1"}]},
      {"SHOW TAG VALUES FROM \"~m6\" WITH KEY = host", []},
      {"SHOW TAG VALUES FROM \"~m7\" WITH KEY IN (a, A, b, B)",
       [
         %{"iox::measurement" => "~m7", "key" => "A", "value" => "4"},
         %{"iox::measurement" => "~m7", "key" => "B", "value" => "2"},
         %{"iox::measurement" => "~m7", "key" => "a", "value" => "3"},
         %{"iox::measurement" => "~m7", "key" => "b", "value" => "1"}
       ]},
      {"SHOW TAG VALUES FROM \"~m3\" WITH KEY = host LIMIT 1",
       [%{"iox::measurement" => "~m3", "key" => "host", "value" => "h1"}]},
      {"SHOW TAG VALUES FROM \"~m3\" WITH KEY = host LIMIT 1 OFFSET 1",
       [%{"iox::measurement" => "~m3", "key" => "host", "value" => "h2"}]},
      {"SHOW TAG VALUES FROM \"~m3\" WITH KEY = host OFFSET 1",
       [%{"iox::measurement" => "~m3", "key" => "host", "value" => "h2"}]},
      {"SHOW TAG VALUES FROM \"~m3\" WITH KEY = host OFFSET 5", []},
      {"SHOW TAG VALUES FROM \"~m3\" WITH KEY = host LIMIT 0", []},
      {"SHOW TAG VALUES FROM \"~m3\" WITH KEY = region LIMIT 1",
       [%{"iox::measurement" => "~m3", "key" => "region", "value" => "east"}]},
      {"SHOW TAG VALUES FROM \"~m3\" WITH KEY = region LIMIT 1 OFFSET 1",
       [%{"iox::measurement" => "~m3", "key" => "region"}]},
      {"SHOW TAG VALUES FROM \"~m3\" WITH KEY = region OFFSET 1",
       [%{"iox::measurement" => "~m3", "key" => "region"}]},
      {"SHOW TAG VALUES FROM \"~m3\" WITH KEY = host WHERE host = 'h1' LIMIT 1 OFFSET 1", []},
      {"SHOW TAG VALUES FROM \"~m3\" WITH KEY = host LIMIT 9223372036854775808",
       [
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h1"},
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h2"}
       ]},
      {"SHOW TAG VALUES FROM \"~m3\" WITH KEY = host OFFSET 9223372036854775808", []},
      {"SHOW TAG VALUES FROM \"~m3\" WITH KEY = host LIMIT 9223372036854775808 OFFSET 1",
       [%{"iox::measurement" => "~m3", "key" => "host", "value" => "h2"}]},
      {"SHOW TAG VALUES FROM \"~m1\" WITH KEY = host LIMIT 1", []},
      {"SHOW TAG VALUES ON ~db FROM \"~m3\" WITH KEY = host",
       [
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h1"},
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h2"}
       ]},
      {"SHOW TAG VALUES ON nope FROM \"~m3\" WITH KEY = host",
       {:error, 400,
        "provided a database in both the parameters (~db) and query string (nope) that do not match, if providing a query that specifies the database, you can omit the 'database' parameter from your request"}},
      {"SHOW TAG VALUES FROM \"~m3\" WITH KEY = host;",
       [
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h1"},
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h2"}
       ]},
      {"show tag values from \"~m3\" with key = host",
       [
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h1"},
         %{"iox::measurement" => "~m3", "key" => "host", "value" => "h2"}
       ]}
    ]
  end

  @doc "`SHOW RETENTION POLICIES`."
  @spec retention() :: [{binary(), [map()] | {:error, pos_integer(), binary()}}]
  def retention do
    [
      {"SHOW RETENTION POLICIES",
       [%{"duration" => "0s", "iox::database" => "~db", "name" => "autogen"}]},
      {"SHOW RETENTION POLICIES ON ~db",
       [%{"duration" => "0s", "iox::database" => "~db", "name" => "autogen"}]},
      {"SHOW RETENTION POLICIES ON \"~db\"",
       [%{"duration" => "0s", "iox::database" => "~db", "name" => "autogen"}]},
      {"SHOW RETENTION POLICIES ON ~db;",
       [%{"duration" => "0s", "iox::database" => "~db", "name" => "autogen"}]},
      {"show retention policies",
       [%{"duration" => "0s", "iox::database" => "~db", "name" => "autogen"}]},
      {"SHOW RETENTION POLICIES ON nope",
       {:error, 400,
        "provided a database in both the parameters (~db) and query string (nope) that do not match, if providing a query that specifies the database, you can omit the 'database' parameter from your request"}}
    ]
  end

  @doc "The statements the engine's parser and planner refuse, with their status and body."
  @spec errors() :: [{binary(), [map()] | {:error, pos_integer(), binary()}}]
  def errors do
    [
      {"SHOW",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 0. Parsing Error: Nom(\"\", Many1)"}},
      {"SHOW;",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 0. Parsing Error: Nom(\";\", Many1)"}},
      {"SHOW ",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid SHOW statement, expected DATABASES, FIELD KEYS, MEASUREMENTS, TAG KEYS, TAG VALUES, or RETENTION POLICIES following SHOW at pos 5"}},
      {"SHOW  ",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid SHOW statement, expected DATABASES, FIELD KEYS, MEASUREMENTS, TAG KEYS, TAG VALUES, or RETENTION POLICIES following SHOW at pos 6"}},
      {"SHOW ;",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid SHOW statement, expected DATABASES, FIELD KEYS, MEASUREMENTS, TAG KEYS, TAG VALUES, or RETENTION POLICIES following SHOW at pos 5"}},
      {"SHOW x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid SHOW statement, expected DATABASES, FIELD KEYS, MEASUREMENTS, TAG KEYS, TAG VALUES, or RETENTION POLICIES following SHOW at pos 5"}},
      {"SHOW SERIES",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid SHOW statement, expected DATABASES, FIELD KEYS, MEASUREMENTS, TAG KEYS, TAG VALUES, or RETENTION POLICIES following SHOW at pos 5"}},
      {"SHOW USERS",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid SHOW statement, expected DATABASES, FIELD KEYS, MEASUREMENTS, TAG KEYS, TAG VALUES, or RETENTION POLICIES following SHOW at pos 5"}},
      {"SHOW MEASUREMENT",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid SHOW statement, expected DATABASES, FIELD KEYS, MEASUREMENTS, TAG KEYS, TAG VALUES, or RETENTION POLICIES following SHOW at pos 5"}},
      {"SHOW TAG",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid SHOW statement, expected DATABASES, FIELD KEYS, MEASUREMENTS, TAG KEYS, TAG VALUES, or RETENTION POLICIES following SHOW at pos 5"}},
      {"SHOW TAG ",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid SHOW TAG statement, expected KEYS or VALUES at pos 9"}},
      {"SHOW TAG x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid SHOW TAG statement, expected KEYS or VALUES at pos 9"}},
      {"SHOW TAG KEY FROM \"m\"",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid SHOW TAG statement, expected KEYS or VALUES at pos 9"}},
      {"SHOW TAGS",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid SHOW statement, expected DATABASES, FIELD KEYS, MEASUREMENTS, TAG KEYS, TAG VALUES, or RETENTION POLICIES following SHOW at pos 5"}},
      {"SHOW FIELD",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid SHOW statement, expected DATABASES, FIELD KEYS, MEASUREMENTS, TAG KEYS, TAG VALUES, or RETENTION POLICIES following SHOW at pos 5"}},
      {"SHOW FIELD x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid SHOW FIELD KEYS statement, expected KEYS at pos 11"}},
      {"SHOW FIELD KEY CARDINALITY",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid SHOW FIELD KEYS statement, expected KEYS at pos 11"}},
      {"SHOW RETENTION",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid SHOW statement, expected DATABASES, FIELD KEYS, MEASUREMENTS, TAG KEYS, TAG VALUES, or RETENTION POLICIES following SHOW at pos 5"}},
      {"SHOW RETENTION x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid SHOW RETENTION POLICIES statement, expected POLICIES at pos 15"}},
      {"SHOW RETENTION POLICY",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid SHOW RETENTION POLICIES statement, expected POLICIES at pos 15"}},
      {"SHOW RETENTION POLICIES LIMIT 1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 24. Parsing Error: Nom(\"LIMIT 1\", Tag)"}},
      {"SHOW RETENTION POLICIES extra",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 24. Parsing Error: Nom(\"extra\", Tag)"}},
      {"SHOW RETENTION POLICIES ON",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid ON clause, expected identifier at pos 26"}},
      {"SHOW RETENTION POLICIES ON 5",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid ON clause, expected identifier at pos 26"}},
      {"SHOW DATABASES LIMIT 1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 15. Parsing Error: Nom(\"LIMIT 1\", Tag)"}},
      {"SHOW DATABASES extra",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 15. Parsing Error: Nom(\"extra\", Tag)"}},
      {"SHOW DATABASES ON x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 15. Parsing Error: Nom(\"ON x\", Tag)"}},
      {"SHOW MEASUREMENTS LIMIT x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid LIMIT clause, expected unsigned integer at pos 24"}},
      {"SHOW MEASUREMENTS LIMIT",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 18. Parsing Error: Nom(\"LIMIT\", Tag)"}},
      {"SHOW MEASUREMENTS LIMIT ",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid LIMIT clause, expected unsigned integer at pos 24"}},
      {"SHOW MEASUREMENTS LIMIT -1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid LIMIT clause, expected unsigned integer at pos 24"}},
      {"SHOW MEASUREMENTS LIMIT 1.5",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 25. Parsing Error: Nom(\".5\", Tag)"}},
      {"SHOW MEASUREMENTS OFFSET x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid OFFSET clause, expected unsigned integer at pos 25"}},
      {"SHOW MEASUREMENTS OFFSET 1 LIMIT 1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 27. Parsing Error: Nom(\"LIMIT 1\", Tag)"}},
      {"SHOW MEASUREMENTS LIMIT 1 LIMIT 1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 26. Parsing Error: Nom(\"LIMIT 1\", Tag)"}},
      {"SHOW MEASUREMENTS extra",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 18. Parsing Error: Nom(\"extra\", Tag)"}},
      {"SHOW MEASUREMENTS  extra  ",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 19. Parsing Error: Nom(\"extra  \", Tag)"}},
      {"SHOW MEASUREMENTS FROM x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 18. Parsing Error: Nom(\"FROM x\", Tag)"}},
      {"SHOW MEASUREMENTS ON",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 18. Parsing Error: Nom(\"ON\", Tag)"}},
      {"SHOW MEASUREMENTS ON ",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid ON clause, expected wildcard or identifier at pos 21"}},
      {"SHOW MEASUREMENTS ON;",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 18. Parsing Error: Nom(\"ON;\", Tag)"}},
      {"SHOW MEASUREMENTS ON 5",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid ON clause, expected wildcard or identifier at pos 21"}},
      {"SHOW MEASUREMENTS ON x y",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 23. Parsing Error: Nom(\"y\", Tag)"}},
      {"SHOW MEASUREMENTS ON *x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\"x\", Tag)"}},
      {"SHOW MEASUREMENTS ON rv.*",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid ON clause, expected wildcard or identifier at pos 21"}},
      {"SHOW MEASUREMENTS WITH",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 18. Parsing Error: Nom(\"WITH\", Tag)"}},
      {"SHOW MEASUREMENTS WITH ",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid WITH clause, expected MEASUREMENT at pos 23"}},
      {"SHOW MEASUREMENTS WITH KEY = x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid WITH clause, expected MEASUREMENT at pos 23"}},
      {"SHOW MEASUREMENTS WITH MEASUREMENT",
       {:error, 400, "error in InfluxQL statement: parsing error: expected = or =~ at pos 34"}},
      {"SHOW MEASUREMENTS WITH MEASUREMENT !~ /x/",
       {:error, 400, "error in InfluxQL statement: parsing error: expected = or =~ at pos 35"}},
      {"SHOW MEASUREMENTS WITH MEASUREMENT != \"x\"",
       {:error, 400, "error in InfluxQL statement: parsing error: expected = or =~ at pos 35"}},
      {"SHOW MEASUREMENTS WITH MEASUREMENT IN (\"x\")",
       {:error, 400, "error in InfluxQL statement: parsing error: expected = or =~ at pos 35"}},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =",
       {:error, 400,
        "error in InfluxQL statement: parsing error: expected measurement name at pos 36"}},
      {"SHOW MEASUREMENTS WITH MEASUREMENT = 5",
       {:error, 400,
        "error in InfluxQL statement: parsing error: expected measurement name at pos 37"}},
      {"SHOW MEASUREMENTS WITH MEASUREMENT = 'x'",
       {:error, 400,
        "error in InfluxQL statement: parsing error: expected measurement name at pos 37"}},
      {"SHOW MEASUREMENTS WITH MEASUREMENT = `x`",
       {:error, 400,
        "error in InfluxQL statement: parsing error: expected measurement name at pos 37"}},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ 'x'",
       {:error, 400,
        "error in InfluxQL statement: parsing error: expected measurement name at pos 36"}},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ 5",
       {:error, 400,
        "error in InfluxQL statement: parsing error: expected measurement name at pos 36"}},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ \"x\"",
       {:error, 400, "Error during planning: expected regex but got string"}},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ x",
       {:error, 400, "Error during planning: expected regex but got string"}},
      {"SHOW MEASUREMENTS WITH MEASUREMENT = /x/",
       {:error, 400, "Error during planning: expected string but got regex"}},
      {"SHOW MEASUREMENTS WITH MEASUREMENT =~ /x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: unterminated regex literal at pos 40"}},
      {"SHOW MEASUREMENTS WITH MEASUREMENT = \"x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: unterminated string literal at pos 39"}},
      {"SHOW MEASUREMENTS WITH MEASUREMENT = a.\"x\"",
       {:error, 405, "This feature is not implemented: retention policy in from clause"}},
      {"SHOW MEASUREMENTS WITH MEASUREMENT = a.b.\"x\"",
       {:error, 405, "This feature is not implemented: database name in from clause"}},
      {"SHOW MEASUREMENTS WITH MEASUREMENT = a..x",
       {:error, 405, "This feature is not implemented: database name in from clause"}},
      {"SHOW MEASUREMENTS WHERE",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 18. Parsing Error: Nom(\"WHERE\", Tag)"}},
      {"SHOW MEASUREMENTS WHERE host =",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid conditional expression at pos 30"}},
      {"SHOW MEASUREMENTS WHERE host = 'a' AND",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid conditional expression at pos 38"}},
      {"SHOW MEASUREMENTS WHERE host = 'a' LIMIT x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid LIMIT clause, expected unsigned integer at pos 41"}},
      {"SHOW MEASUREMENTS WHERE host = 'a' LIMIT 1 extra",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 43. Parsing Error: Nom(\"extra\", Tag)"}},
      {"SHOW MEASUREMENTS WHERE host = 'a' OFFSET 1 LIMIT 1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 44. Parsing Error: Nom(\"LIMIT 1\", Tag)"}},
      {"SHOW MEASUREMENTS WHERE host =~ 'x'",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid conditional, expected regular expression at pos 31"}},
      {"SHOW MEASUREMENTS WHERE time > 'x'",
       {:error, 400,
        "Error during planning: invalid expression \"'x'\": 'x' is not a valid timestamp"}},
      {"SHOW MEASUREMENTS WHERE ((host = 'a')",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 18. Parsing Error: Nom(\"WHERE ((host = 'a')\", Tag)"}},
      {"SHOW MEASUREMENTS WHERE host = 'a')",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 34. Parsing Error: Nom(\")\", Tag)"}},
      {"SHOW MEASUREMENTS WHERE NOT host = 'a'",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 28. Parsing Error: Nom(\"host = 'a'\", Tag)"}},
      {"SHOW MEASUREMENTS WHERE host = 'a' GROUP BY host",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 35. Parsing Error: Nom(\"GROUP BY host\", Tag)"}},
      {"SHOW MEASUREMENTS WHERE host = 'a' ORDER BY time",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 35. Parsing Error: Nom(\"ORDER BY time\", Tag)"}},
      {"SHOW MEASUREMENTS WHERE 'unterminated",
       {:error, 400,
        "error in InfluxQL statement: parsing error: unterminated string literal at pos 37"}},
      {"SHOW MEASUREMENTS LIMIT 18446744073709551616",
       {:error, 400,
        "error in InfluxQL statement: parsing error: unable to parse unsigned integer at pos 44"}},
      {"SHOW MEASUREMENTS OFFSET 18446744073709551616",
       {:error, 400,
        "error in InfluxQL statement: parsing error: unable to parse unsigned integer at pos 45"}},
      {"SHOW MEASUREMENTS LIMIT 9223372036854775808",
       {:error, 400,
        "Optimizer rule 'eliminate_limit' failed\ncaused by\nError during planning: LIMIT must be >= 0, '-9223372036854775808' was provided"}},
      {"SHOW MEASUREMENTS LIMIT 18446744073709551615",
       {:error, 400,
        "Optimizer rule 'eliminate_limit' failed\ncaused by\nError during planning: LIMIT must be >= 0, '-1' was provided"}},
      {"SHOW MEASUREMENTS OFFSET 9223372036854775808",
       {:error, 400,
        "Optimizer rule 'eliminate_limit' failed\ncaused by\nError during planning: OFFSET must be >=0, '-9223372036854775808' was provided"}},
      {"SHOW MEASUREMENTS OFFSET 18446744073709551615",
       {:error, 400,
        "Optimizer rule 'eliminate_limit' failed\ncaused by\nError during planning: OFFSET must be >=0, '-1' was provided"}},
      {"SHOW MEASUREMENTS LIMIT 1 OFFSET 9223372036854775808",
       {:error, 400,
        "Optimizer rule 'push_down_limit' failed\ncaused by\nError during planning: OFFSET must be >=0, '-9223372036854775808' was provided"}},
      {"SHOW MEASUREMENTS LIMIT 9223372036854775808 OFFSET 9223372036854775808",
       {:error, 400,
        "Optimizer rule 'eliminate_limit' failed\ncaused by\nError during planning: LIMIT must be >= 0, '-9223372036854775808' was provided"}},
      {"SHOW MEASUREMENTS LIMIT 18446744073709551615 OFFSET 1",
       {:error, 400,
        "Optimizer rule 'eliminate_limit' failed\ncaused by\nError during planning: LIMIT must be >= 0, '-1' was provided"}},
      {"SHOW MEASUREMENTS WITH MEASUREMENT = \"nope\" LIMIT 9223372036854775808",
       {:error, 400,
        "Optimizer rule 'eliminate_limit' failed\ncaused by\nError during planning: LIMIT must be >= 0, '-9223372036854775808' was provided"}},
      {"SHOW MEASUREMENTS WITH MEASUREMENT = \"nope\" WHERE time > 0 LIMIT 9223372036854775808",
       {:error, 400,
        "Optimizer rule 'eliminate_limit' failed\ncaused by\nError during planning: LIMIT must be >= 0, '-9223372036854775808' was provided"}},
      {"SHOW MEASUREMENTS; SHOW MEASUREMENTS",
       {:error, 400, "must provide only one InfluxQl statement per query"}},
      {"SHOW MEASUREMENTS; SHOW MEASUREMENTS LIMIT x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid LIMIT clause, expected unsigned integer at pos 43"}},
      {"SHOW MEASUREMENTS; foo",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 19. Parsing Error: Nom(\"foo\", Tag)"}},
      {"SHOW MEASUREMENTS /* c */ extra",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 26. Parsing Error: Nom(\"extra\", Tag)"}},
      {"SHOW MEASUREMENTS extra /* c */ more",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 18. Parsing Error: Nom(\"extra /* c */ more\", Tag)"}},
      {"SHOW MEASUREMENTS extra -- c",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 18. Parsing Error: Nom(\"extra -- c\", Tag)"}},
      {"SHOW MEASUREMENTS LIMIT /* c */ x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid LIMIT clause, expected unsigned integer at pos 32"}},
      {"SHOW MEASUREMENTS WHERE host = /* c */",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid conditional expression at pos 30"}},
      {"SHOW /* x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid inline comment, missing closing */ at pos 7"}},
      {"SHOW MEASUREMENTS /* x */ /* y",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid inline comment, missing closing */ at pos 28"}},
      {"SHOW TAG KEYS FROM",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 14. Parsing Error: Nom(\"FROM\", Tag)"}},
      {"SHOW TAG KEYS FROM ",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid FROM clause, expected identifier or regular expression at pos 19"}},
      {"SHOW TAG KEYS FROM 5",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid FROM clause, expected identifier or regular expression at pos 19"}},
      {"SHOW TAG KEYS FROM 'x'",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid FROM clause, expected identifier or regular expression at pos 19"}},
      {"SHOW TAG KEYS FROM 9a",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid FROM clause, expected identifier or regular expression at pos 19"}},
      {"SHOW TAG KEYS FROM limit",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid FROM clause, expected identifier or regular expression at pos 19"}},
      {"SHOW TAG KEYS FROM show",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid FROM clause, expected identifier or regular expression at pos 19"}},
      {"SHOW TAG KEYS FROM \"m\",",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\",\", Tag)"}},
      {"SHOW TAG KEYS FROM \"m\", ",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\", \", Tag)"}},
      {"SHOW TAG KEYS FROM \"m\",,\"n\"",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 22. Parsing Error: Nom(\",,\\\"n\\\"\", Tag)"}},
      {"SHOW TAG KEYS FROM \"m\" \"n\"",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 23. Parsing Error: Nom(\"\\\"n\\\"\", Tag)"}},
      {"SHOW TAG KEYS FROM \"a\\_b\"",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid escape sequence, expected \\\\, \\\" or \\n at pos 22"}},
      {"SHOW TAG KEYS FROM /a",
       {:error, 400,
        "error in InfluxQL statement: parsing error: unterminated regex literal at pos 21"}},
      {"SHOW TAG KEYS FROM m.n",
       {:error, 405, "This feature is not implemented: retention policy in from clause"}},
      {"SHOW TAG KEYS FROM m.n.o",
       {:error, 405, "This feature is not implemented: database name in from clause"}},
      {"SHOW TAG KEYS FROM rv_test..m",
       {:error, 405, "This feature is not implemented: database name in from clause"}},
      {"SHOW TAG KEYS FROM \"rv_test\".\"autogen\".\"m\"",
       {:error, 405, "This feature is not implemented: database name in from clause"}},
      {"SHOW TAG KEYS FROM \"m\" extra",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 23. Parsing Error: Nom(\"extra\", Tag)"}},
      {"SHOW TAG KEYS extra",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 14. Parsing Error: Nom(\"extra\", Tag)"}},
      {"SHOW TAG KEYS ON",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid ON clause, expected identifier at pos 16"}},
      {"SHOW TAG KEYS ON ",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid ON clause, expected identifier at pos 16"}},
      {"SHOW TAG KEYS ON;",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid ON clause, expected identifier at pos 16"}},
      {"SHOW TAG KEYS ON 5",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid ON clause, expected identifier at pos 16"}},
      {"SHOW TAG KEYS ON a.b FROM \"m\"",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 18. Parsing Error: Nom(\".b FROM \\\"m\\\"\", Tag)"}},
      {"SHOW TAG KEYS FROM \"m\" LIMIT x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid LIMIT clause, expected unsigned integer at pos 29"}},
      {"SHOW TAG KEYS FROM \"m\" LIMIT -1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid LIMIT clause, expected unsigned integer at pos 29"}},
      {"SHOW TAG KEYS FROM \"m\" LIMIT 1.5",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 30. Parsing Error: Nom(\".5\", Tag)"}},
      {"SHOW TAG KEYS FROM \"m\" LIMIT",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 23. Parsing Error: Nom(\"LIMIT\", Tag)"}},
      {"SHOW TAG KEYS FROM \"m\" LIMIT;",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 23. Parsing Error: Nom(\"LIMIT;\", Tag)"}},
      {"SHOW TAG KEYS FROM \"m\" OFFSET x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid OFFSET clause, expected unsigned integer at pos 30"}},
      {"SHOW TAG KEYS FROM \"m\" OFFSET 1 LIMIT 1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 32. Parsing Error: Nom(\"LIMIT 1\", Tag)"}},
      {"SHOW TAG KEYS FROM \"m\" LIMIT 1 OFFSET ",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid OFFSET clause, expected unsigned integer at pos 38"}},
      {"SHOW TAG KEYS FROM \"m\" LIMIT 1 OFFSET",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 31. Parsing Error: Nom(\"OFFSET\", Tag)"}},
      {"SHOW TAG KEYS FROM \"m\" LIMIT 1 WHERE host = 'a'",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 31. Parsing Error: Nom(\"WHERE host = 'a'\", Tag)"}},
      {"SHOW TAG KEYS FROM \"m\" SLIMIT 1",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 23. Parsing Error: Nom(\"SLIMIT 1\", Tag)"}},
      {"SHOW TAG KEYS FROM \"m\" ORDER BY time",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 23. Parsing Error: Nom(\"ORDER BY time\", Tag)"}},
      {"SHOW TAG KEYS FROM \"m\" GROUP BY host",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 23. Parsing Error: Nom(\"GROUP BY host\", Tag)"}},
      {"SHOW TAG KEYS FROM \"m\" WHERE",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 23. Parsing Error: Nom(\"WHERE\", Tag)"}},
      {"SHOW TAG KEYS FROM \"m\" WHERE ",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 23. Parsing Error: Nom(\"WHERE \", Tag)"}},
      {"SHOW TAG KEYS FROM \"m\" WHERE host =",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid conditional expression at pos 35"}},
      {"SHOW TAG KEYS FROM \"m\" WHERE ((host = 'a')",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 23. Parsing Error: Nom(\"WHERE ((host = 'a')\", Tag)"}},
      {"SHOW TAG KEYS FROM \"m\" WHERE host = 'a')",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 39. Parsing Error: Nom(\")\", Tag)"}},
      {"SHOW TAG KEYS FROM \"m\" WHERE host = 'a' AND",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid conditional expression at pos 43"}},
      {"SHOW TAG KEYS FROM \"m\" WHERE NOT host = 'a'",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 33. Parsing Error: Nom(\"host = 'a'\", Tag)"}},
      {"SHOW TAG KEYS FROM \"m\" WHERE host = 'a' GROUP BY host",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 40. Parsing Error: Nom(\"GROUP BY host\", Tag)"}},
      {"SHOW TAG KEYS FROM \"m\" WHERE time > 'x'", []},
      {"SHOW TAG KEYS FROM \"m\" LIMIT 18446744073709551616",
       {:error, 400,
        "error in InfluxQL statement: parsing error: unable to parse unsigned integer at pos 49"}},
      {"SHOW FIELD KEYS FROM",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 16. Parsing Error: Nom(\"FROM\", Tag)"}},
      {"SHOW FIELD KEYS LIMIT x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid LIMIT clause, expected unsigned integer at pos 22"}},
      {"SHOW FIELD KEYS extra   ",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 16. Parsing Error: Nom(\"extra   \", Tag)"}},
      {"SHOW FIELD KEYS ON ",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid ON clause, expected identifier at pos 18"}},
      {"SHOW FIELD KEYS WHERE host = 'a'",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 16. Parsing Error: Nom(\"WHERE host = 'a'\", Tag)"}},
      {"SHOW TAG VALUES",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid SHOW TAG VALUES statement, expected WITH KEY clause at pos 15"}},
      {"SHOW TAG VALUES ",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid SHOW TAG VALUES statement, expected WITH KEY clause at pos 15"}},
      {"SHOW TAG VALUES FROM \"m\"",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid SHOW TAG VALUES statement, expected WITH KEY clause at pos 24"}},
      {"SHOW TAG VALUES FROM \"m\" ",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid SHOW TAG VALUES statement, expected WITH KEY clause at pos 24"}},
      {"SHOW TAG VALUES FROM \"m\" WITH",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid SHOW TAG VALUES statement, expected WITH KEY clause at pos 24"}},
      {"SHOW TAG VALUES FROM \"m\" WITH ",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid WITH KEY clause, expected KEY at pos 30"}},
      {"SHOW TAG VALUES FROM \"m\" WITH KEY",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid WITH KEY clause, expected condition at pos 33"}},
      {"SHOW TAG VALUES FROM \"m\" WITH KEY x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid WITH KEY clause, expected condition at pos 33"}},
      {"SHOW TAG VALUES FROM \"m\" WITH KEY =",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid WITH KEY clause, expected identifier following = at pos 35"}},
      {"SHOW TAG VALUES FROM \"m\" WITH KEY = 'host'",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid WITH KEY clause, expected identifier following = at pos 35"}},
      {"SHOW TAG VALUES FROM \"m\" WITH KEY = 5",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid WITH KEY clause, expected identifier following = at pos 35"}},
      {"SHOW TAG VALUES FROM \"m\" WITH KEY =~ host",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid WITH KEY clause, expected regular expression following =~ at pos 37"}},
      {"SHOW TAG VALUES FROM \"m\" WITH KEY =~ 'h'",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid WITH KEY clause, expected regular expression following =~ at pos 37"}},
      {"SHOW TAG VALUES FROM \"m\" WITH KEY < host",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid WITH KEY clause, expected condition at pos 33"}},
      {"SHOW TAG VALUES FROM \"m\" WITH KEY in (host)",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid WITH KEY clause, expected condition at pos 33"}},
      {"SHOW TAG VALUES FROM \"m\" WITH KEY IN host",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid WITH KEY clause, expected identifier list following IN at pos 36"}},
      {"SHOW TAG VALUES FROM \"m\" WITH KEY IN ()",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid IN clause, expected identifier at pos 38"}},
      {"SHOW TAG VALUES FROM \"m\" WITH KEY IN (host",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid identifier list, expected ')' at pos 42"}},
      {"SHOW TAG VALUES FROM \"m\" WITH KEY IN (host,)",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid identifier list, expected ')' at pos 42"}},
      {"SHOW TAG VALUES FROM \"m\" WITH KEY IN ('host')",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid IN clause, expected identifier at pos 38"}},
      {"SHOW TAG VALUES FROM \"m\" WITH KEY = host extra",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 41. Parsing Error: Nom(\"extra\", Tag)"}},
      {"SHOW TAG VALUES FROM \"m\" WITH KEY = host LIMIT x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid LIMIT clause, expected unsigned integer at pos 47"}},
      {"SHOW TAG VALUES FROM \"m\" WITH KEY = host OFFSET x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid OFFSET clause, expected unsigned integer at pos 48"}},
      {"SHOW TAG VALUES FROM \"m\" WITH KEY = host LIMIT 1 OFFSET x",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid OFFSET clause, expected unsigned integer at pos 56"}},
      {"SHOW TAG VALUES WITH KEY = host WHERE",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid InfluxQL statement at pos 32. Parsing Error: Nom(\"WHERE\", Tag)"}},
      {"SHOW TAG VALUES ON",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid ON clause, expected identifier at pos 18"}},
      {"SHOW TAG VALUES ON rv_test",
       {:error, 400,
        "error in InfluxQL statement: parsing error: invalid SHOW TAG VALUES statement, expected WITH KEY clause at pos 26"}}
    ]
  end
end
