defmodule InfluxElixir.Contract.SQLScalarRefusals do
  @moduledoc """
  The cases of the `*_refusable` tables that `Client.Local` refuses by name instead
  of answering, as `{kind, text}`: the pin of the ratchet in
  `InfluxElixir.Contract.SQLScalar`.

  The pin is a set of cases, not a number of them. A case that is refused now and
  is not listed has regressed; a case that is listed and is answered now has been
  fixed, and moves out of its refusable table into the table of answers (and out of
  the list here). Swapping one for another fails twice, once for each, where a count
  would hold. A real engine refuses none of them.

  To list the cases of a table: run it against `Client.Local`, and keep the ones for
  which `InfluxElixir.Contract.SQLScalar.refusal?/1` holds of the answer.
  """

  @doc "The cases refused of `expressions_values_refusable/0` of `SQLScalarCases`."
  @spec expressions_values() :: [{atom(), binary()}]
  def expressions_values do
    [
      {:sel, "s ~ 's[01]'"},
      {:sel, "s !~ 's[01]'"},
      {:sel, "s ~* 'S1'"},
      {:raw, "SELECT u, CASE WHEN u > 3 THEN u ELSE 0 END AS a FROM mext ORDER BY time"},
      {:raw, "SELECT u, pow(u, 2) AS a FROM mext ORDER BY time"},
      {:sel, "greatest(time, time)"},
      {:sel, "coalesce(time, time)"},
      {:sel, "nullif(time, time)"},
      {:sel, "length(time)"},
      {:sel, "CASE WHEN b THEN time ELSE time END"},
      {:sel, "time || 'a'"},
      {:sel, "CASE time WHEN '2023-11-14T22:13:20Z' THEN 'a' END"}
    ]
  end

  @doc "The cases refused of `expressions_names_refusable/0` of `SQLScalarCases`."
  @spec expressions_names() :: [{atom(), binary()}]
  def expressions_names do
    [
      {:raw, "SELECT CAST(n AS BIGINT UNSIGNED) FROM main WHERE n = 4"}
    ]
  end

  @doc "The cases refused of `functions_values_refusable/0` of `SQLScalarCases`."
  @spec functions_values() :: [{atom(), binary()}]
  def functions_values do
    [
      {:sel, "pow(1.0e300 * 1.0e300, 2.0)"},
      {:sel, "pow(2.0, 1.0e300 * 1.0e300)"},
      {:sel, "pow(2, 1.0e300 * 1.0e300)"},
      {:sel, "pow(length(s), 2)"},
      {:sel, "greatest(length(s), 1)"},
      {:raw, "SELECT log(CAST(n AS DOUBLE), n) AS r FROM main ORDER BY time"},
      {:raw, "SELECT log(CAST(x AS DOUBLE), x) AS r FROM main ORDER BY time"},
      {:raw, "SELECT log(u, u) AS r FROM mext ORDER BY time"}
    ]
  end

  @doc "The cases refused of `errors_refusable/0` of `SQLScalarCases`."
  @spec errors() :: [{atom(), binary()}]
  def errors do
    [
      {:sel, "coalesce(x, s)"},
      {:sel, "coalesce(s, n, x)"},
      {:sel, "nullif(host, n)"},
      {:sel, "greatest(b, n)"},
      {:sel, "least(time, 1)"},
      {:sel, "lower(time)"},
      {:sel, "CASE WHEN b THEN time ELSE 1 END"},
      {:sel, "CASE WHEN b THEN time ELSE 's' END"},
      {:sel, "starts_with(time, 'a')"},
      {:sel, "greatest(1, 'a')"},
      {:sel, "greatest(n, true)"},
      {:sel, "substr('a')"},
      {:sel, "log(x, x, x)"},
      {:sel, "log(s)"},
      {:sel, "log(b)"},
      {:sel, "log(2, s)"},
      {:sel, "greatest(s, n)"},
      {:sel, "least(s, b)"},
      {:sel, "greatest(x, n, s)"},
      {:where, "substr(s) = 'a'"},
      {:where, "log(s) > 1"},
      {:where, "greatest(s, n) = 1"},
      {:order, "substr(s)"},
      {:order, "greatest(s, n)"},
      {:order, "log(s)"},
      {:raw, "SELECT CAST(substr(s) AS INT) FROM main"},
      {:raw, "SELECT substr(s) IS NULL FROM main"},
      {:sel, "log(host, host)"},
      {:sel, "log(s, s)"},
      {:sel, "log(b, b)"},
      {:sel, "CASE WHEN s THEN 1 END"},
      {:sel, "CASE WHEN n > 1 THEN 1 WHEN n > 2 THEN true ELSE 3 END"},
      {:sel, "coalesce(n, s)"},
      {:sel, "coalesce(n, x, s)"},
      {:sel, "coalesce(host, 1)"},
      {:sel, "nullif(n, s)"},
      {:sel, "nullif(s, 1)"},
      {:sel, "nullif(x, s)"},
      {:sel, "time = 'abc'"},
      {:where, "s LIKE n"},
      {:where, "coalesce(n, s) > 1"},
      {:where, "nullif(n, s) > 1"},
      {:where, "time > n"},
      {:where, "time < x"},
      {:order, "coalesce(n, s)"},
      {:order, "nullif(n, s)"},
      {:sel, "x IS UNKNOWN"},
      {:sel, "CASE time WHEN 's' THEN 'a' END"},
      {:sel, "CASE time WHEN s THEN 'a' END"},
      {:sel, "CASE s WHEN time THEN 'a' END"},
      {:sel, "CASE host WHEN time THEN 'a' END"},
      {:raw, "replace into m values (1)"},
      {:raw, "select +s from main limit 1"},
      {:raw, "select log('a',NULL) from main"},
      {:raw, "select log(NULL,'a') from main"},
      {:raw, "select log(NULL,host) from main"},
      {:raw, "select log(NULL,time) from main"},
      {:raw, "select log(NULL,true) from main"},
      {:raw, "select log(host,NULL) from main"},
      {:raw, "select log(time,NULL) from main"},
      {:raw, "select log(true,NULL) from main"},
      {:raw, "select starts_with(NULL,time) from main"},
      {:raw, "select starts_with(time,NULL) from main"},
      {:raw, "SELECT NULL - time - time AS r FROM main"},
      {:raw, "SELECT v FROM main WHERE NULL - time > 0"},
      {:raw, "SELECT coalesce(NULL + NULL, s) AS r FROM main ORDER BY time"},
      {:raw, "SELECT max(+NULL) AS r FROM main"},
      {:raw, "SELECT avg(+NULL) AS r FROM main"},
      {:raw, "SELECT count(+NULL) AS r FROM main"},
      {:raw, "SELECT approx_median(-NULL) AS r FROM main"},
      {:raw, "SELECT v FROM main WHERE NULL - time > 0 ORDER BY time"},
      {:raw, "SELECT v FROM main WHERE time - NULL > 0 ORDER BY time"},
      {:raw, "SELECT coalesce(NULL + NULL, s) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT coalesce(NULL - NULL, s) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT coalesce(NULL + NULL, host) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT coalesce(NULL + NULL, time) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT log(CAST(NULL AS INT), 2) AS r"},
      {:raw, "SELECT log(CAST(NULL AS BIGINT), 2.0) AS r"},
      {:raw, "SELECT arrow_typeof(NULL + NULL) AS r"},
      {:raw, "SELECT arrow_typeof(NULL - NULL) AS r"},
      {:raw, "SELECT arrow_typeof(NULL * 1) AS r"},
      {:raw, "SELECT arrow_typeof(-NULL) AS r"},
      {:raw, "SELECT arrow_typeof(+NULL) AS r"},
      {:raw, "SELECT arrow_typeof(NULL + 1.5) AS r"},
      {:raw, "SELECT arrow_typeof(NULL % NULL) AS r"},
      {:raw, "SELECT arrow_typeof(NULL / NULL) AS r"},
      {:raw, "SELECT arrow_typeof(NULL + time) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT arrow_typeof(NULL - time) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT arrow_typeof(time - NULL) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT arrow_typeof(NULL - time - time) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT arrow_typeof(time - time) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT arrow_typeof(CASE WHEN true THEN NULL END) AS r"},
      {:raw, "SELECT arrow_typeof(NULLIF(NULL, NULL)) AS r"},
      {:raw, "SELECT arrow_typeof(NULLIF(1, NULL)) AS r"},
      {:raw, "SELECT arrow_typeof(coalesce(NULL, NULL)) AS r"},
      {:raw,
       "SELECT arrow_typeof(coalesce(NULL + NULL, s)) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT arrow_typeof(coalesce(NULL + NULL, 1)) AS r"},
      {:raw, "SELECT arrow_typeof(CAST(NULL AS DOUBLE)) AS r"},
      {:raw, "SELECT arrow_typeof(CAST(NULL AS INT)) AS r"},
      {:raw, "SELECT arrow_typeof(NULL) AS r"},
      {:raw, "SELECT arrow_typeof(NULL::int) AS r"},
      {:raw, "SELECT arrow_typeof(NULL + n) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT arrow_typeof(NULL - n) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT arrow_typeof(NULL - x) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT arrow_typeof(NULL - s) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT arrow_typeof(NULL + b) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT arrow_typeof(NULL || NULL) AS r"},
      {:raw, "SELECT arrow_typeof(NULL AND NULL) AS r"},
      {:raw, "SELECT arrow_typeof(NULL > NULL) AS r"},
      {:raw, "SELECT arrow_typeof(abs(NULL)) AS r"},
      {:raw, "SELECT arrow_typeof(lower(NULL)) AS r"},
      {:raw, "SELECT arrow_typeof(left(s, NULL + NULL)) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT arrow_typeof(log(CAST(NULL AS DOUBLE), 1)) AS r"},
      {:raw, "SELECT pow(CAST(NULL AS BIGINT UNSIGNED), NULL) AS r"},
      {:raw, "SELECT pow(CAST(NULL AS INT UNSIGNED), NULL) AS r"},
      {:raw, "SELECT pow(NULL, CAST(NULL AS BIGINT UNSIGNED)) AS r"},
      {:raw, "SELECT log(CAST(NULL AS DOUBLE), 2.5) AS r"},
      {:raw, "SELECT log(CAST(NULL AS DOUBLE), n) AS r FROM main ORDER BY time LIMIT 2"},
      {:raw, "SELECT log(CAST(NULL AS DOUBLE), x) AS r FROM main ORDER BY time LIMIT 2"},
      {:raw, "SELECT log(CAST(NULL AS DOUBLE), 0) AS r"},
      {:raw, "SELECT log(CAST(NULL AS DOUBLE), -1) AS r"},
      {:raw, "SELECT log(CAST(NULL AS DOUBLE), 10) AS r"},
      {:raw, "SELECT log(CAST(NULL AS FLOAT), 1) AS r"},
      {:raw, "SELECT left(time, 1) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT left(time, NULLIF(1, 1)) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw,
       "SELECT left(time, CASE WHEN false THEN 1 END) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT left(time, (SELECT 1)) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT length(time) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT lower(time) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT starts_with(time, NULL) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT log(CAST(NULL AS DOUBLE), -0) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT log(CAST(NULL AS DOUBLE), 3) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT log(CAST(NULL AS DOUBLE), 'a') AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT log(CAST(NULL AS DOUBLE), true) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT log(CAST(NULL AS DOUBLE), time) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT log(NULLIF(NULL, NULL), 1) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT log(host, 1) AS r FROM main ORDER BY time LIMIT 2"},
      {:raw, "SELECT log(s, 1) AS r FROM main ORDER BY time LIMIT 2"},
      {:raw, "SELECT log(b, 1) AS r FROM main ORDER BY time LIMIT 2"},
      {:raw, "SELECT log(time, 1) AS r FROM main ORDER BY time LIMIT 2"},
      {:raw, "SELECT log(1, 1, 1) AS r FROM main ORDER BY time LIMIT 2"},
      {:raw, "SELECT abs(NULL - time) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT sqrt(NULL - time) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT lower(NULL - time) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT CAST(NULL - time AS BIGINT) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT coalesce(NULL - time, 1) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT max(NULL - time) AS r FROM main"},
      {:raw, "SELECT sum(NULL - time) AS r FROM main"},
      {:raw, "SELECT avg(NULL - time) AS r FROM main"},
      {:raw, "SELECT count(NULL - time) AS r FROM main"},
      {:raw, "SELECT -(NULL - time) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT (NULL - time) + 1 AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT (NULL - time) * 2 AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT (NULL - time) = (NULL - time) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT v FROM main WHERE (NULL - time) > 0 ORDER BY time"},
      {:raw, "SELECT v FROM main WHERE (NULL - time) = (NULL - time) ORDER BY time"},
      {:raw, "SELECT v FROM main WHERE (NULL - time) > 'a' ORDER BY time"},
      {:raw, "SELECT v FROM main WHERE (NULL - time) > NULL ORDER BY time"},
      {:raw, "SELECT v FROM main WHERE (NULL - time) > CAST(1 AS BIGINT) ORDER BY time"},
      {:raw, "SELECT v FROM main WHERE (NULL - time) BETWEEN 1 AND 2 ORDER BY time"},
      {:raw, "SELECT v FROM main WHERE (NULL - time) IN (1, 2) ORDER BY time"},
      {:raw, "SELECT NULL - time - 1 AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT 1 - (NULL - time) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT (NULL - time) - (NULL - time) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT (NULL - time) || 'a' AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT CASE WHEN true THEN NULL - time END AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT greatest(NULL - time, NULL - time) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT nullif(NULL - time, 1) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT NULL - time - time AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT NULL - time + time AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT time - NULL - time AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT time - NULL + 1 AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT CAST(NULL AS TIMESTAMP) - time AS r FROM main ORDER BY time LIMIT 1"},
      {:raw,
       "SELECT arrow_typeof(CAST(NULL AS TIMESTAMP) - time) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT +NULL AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT +(NULL + NULL) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT +CAST(NULL AS DOUBLE) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT +(-NULL) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT -(+NULL) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT +coalesce(NULL, NULL) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT +CASE WHEN false THEN NULL END AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT +NULLIF(NULL, NULL) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT +n AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT +time AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT + + n AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT +abs(NULL) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT +lower(NULL) AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT v FROM main WHERE +NULL > 1"},
      {:raw, "SELECT v FROM main WHERE +NULL IS NULL"},
      {:raw, "SELECT v FROM main ORDER BY +NULL, time"},
      {:raw, "SELECT sum(+NULL) AS r FROM main"},
      {:raw, "SELECT 1 LIKE host AS r FROM main ORDER BY time LIMIT 3"},
      {:raw, "SELECT n LIKE host AS r FROM main ORDER BY time LIMIT 3"},
      {:raw, "SELECT x LIKE host AS r FROM main ORDER BY time LIMIT 3"},
      {:raw, "SELECT 1.5 LIKE host AS r FROM main ORDER BY time LIMIT 3"},
      {:raw, "SELECT 1 NOT LIKE host AS r FROM main ORDER BY time LIMIT 3"},
      {:raw, "SELECT 1 ILIKE host AS r FROM main ORDER BY time LIMIT 3"},
      {:raw, "SELECT n ILIKE host AS r FROM main ORDER BY time LIMIT 3"},
      {:raw, "SELECT v FROM main WHERE 1 LIKE host"},
      {:raw, "SELECT v FROM main WHERE n LIKE host"},
      {:raw, "SELECT v FROM main WHERE NULL LIKE 1"},
      {:raw, "SELECT v FROM main WHERE time LIKE NULL"},
      {:raw, "SELECT s IS DISTINCT FROM time AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT host IS DISTINCT FROM time AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT v FROM main WHERE time IS NOT DISTINCT FROM 'a'"},
      {:raw, "SELECT n LIKE region AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT v LIKE host AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT 1 LIKE region AS r FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT n NOT LIKE host AS r FROM main ORDER BY time LIMIT 3"},
      {:raw, "SELECT time IS DISTINCT FROM s AS r FROM main ORDER BY time LIMIT 2"},
      {:raw, "SELECT time IS DISTINCT FROM host AS r FROM main ORDER BY time LIMIT 2"},
      {:raw, "SELECT time IS DISTINCT FROM (host || 'x') AS r FROM main ORDER BY time LIMIT 2"},
      {:raw, "SELECT time IS DISTINCT FROM lower(s) AS r FROM main ORDER BY time LIMIT 2"},
      {:raw, "SELECT time = 'a' AS r FROM main ORDER BY time LIMIT 2"},
      {:raw, "SELECT time = s AS r FROM main ORDER BY time LIMIT 2"},
      {:raw, "SELECT time = host AS r FROM main ORDER BY time LIMIT 2"},
      {:raw, "SELECT 1 FROM " <> String.duplicate("a", 4100)},
      {:raw, "SELECT 1 FROM \"" <> String.duplicate("a", 4100) <> "\""},
      {:raw,
       "SELECT host LIKE '" <>
         String.duplicate("a", 70_000) <> "' AS r FROM main ORDER BY time LIMIT 1"},
      {:raw,
       "SELECT v FROM main WHERE host LIKE '" <>
         String.duplicate("a", 70_000) <> "' ORDER BY time"},
      {:sel, "+(n < 1)"},
      {:raw, "SELECT abs(time - NULL) AS a, coalesce(true, 5) AS c FROM main"},
      {:raw, "SELECT abs(time - NULL) AS a, n + 's' AS c FROM main"},
      {:raw, "select host, sum(u) y from mext group by host having -y AND true order by host"},
      {:raw, "select host, sum(u) y from mext group by host having -y order by host"},
      {:raw, "select u from mext where (u / -1) = b"}
    ]
  end

  @doc "The cases refused of `aggregates_refusable/0` of `SQLCatalogCases`."
  @spec aggregates() :: [{atom(), binary()}]
  def aggregates do
    [
      {:raw, "SELECT sum(i / u) + 'a' AS r FROM mext"},
      {:raw, "SELECT avg(i / u) + 'a' AS r FROM mext"},
      {:raw, "SELECT host, sum(n) AS s FROM main GROUP BY host HAVING sum(n)"},
      {:raw, "SELECT host, sum(n) AS s FROM main GROUP BY host HAVING host"},
      {:raw, "SELECT host, sum(n) AS s FROM main GROUP BY host ORDER BY count(*), host"},
      {:raw, "SELECT n AS a, n AS a FROM main WHERE n < 3"},
      {:raw, "SELECT n a, n a FROM main WHERE n < 3"},
      {:raw, "SELECT n, n FROM main WHERE n < 3"},
      {:raw, "SELECT *, n + 1 AS p FROM main WHERE n = 1"},
      {:raw, "SELECT count(*) FROM main HAVING nosuch > 1"},
      {:raw, "SELECT n + 1 AS a, sum(v) AS s FROM main GROUP BY host"},
      {:raw, "SELECT host || 'x' AS a, sum(v) AS s FROM main GROUP BY region"},
      {:raw, "SELECT host, n, sum(v) FROM main GROUP BY host || 'x'"},
      {:raw, "SELECT host, n, sum(v) FROM main GROUP BY upper(host)"},
      {:raw,
       "SELECT date_bin(interval '1 minute', time) AS t, host, n, sum(v) FROM main GROUP BY date_bin(interval '1 minute', time), host"},
      {:raw,
       "SELECT date_bin(interval '1 day', time) AS t, n, sum(v) FROM main GROUP BY date_bin(interval '1 day', time)"},
      {:raw,
       "SELECT date_bin(interval '1 minute', time) AS t, sum(v) FROM main GROUP BY date_bin(interval '1 minute', time) HAVING region = 'r0'"},
      {:raw, "SELECT host, sum(v) + sum(n) AS t, n FROM main GROUP BY host"},
      {:raw, "SELECT host, first_value(n) AS t, n FROM main GROUP BY host"},
      {:raw, "SELECT host, selector_first(n, time) AS t, n FROM main GROUP BY host"},
      {:raw, "SELECT host, sum(v) * 2 AS t, n FROM main GROUP BY host"},
      {:raw, "SELECT host, approx_median(n) AS t, region FROM main GROUP BY host"},
      {:raw, "SELECT host, array_agg(n) AS t, region FROM main GROUP BY host"},
      {:raw, "SELECT avg(DISTINCT n) + 1 AS r FROM main"},
      {:raw, "select count(distinct n, v) from main"},
      {:raw, "select selector_max(v) from main"},
      {:raw, "select selector_max(v, 'a') from main"},
      {:raw, "select selector_max(v, time + 1) from main"},
      {:raw, "SELECT DISTINCT host FROM main HAVING host = 'h1'"},
      {:raw, "SELECT selector_max(1, time) AS r FROM main"},
      {:raw, "SELECT selector_max(true, time) AS r FROM main"},
      {:raw, "SELECT selector_max(NULL, time) AS r FROM main"},
      {:raw, "SELECT selector_first(1, time)['value'] AS r FROM main"},
      {:raw, "SELECT selector_max(n, 1.5) AS r FROM main"},
      {:raw, "SELECT selector_max(n, 'a') AS r FROM main"},
      {:raw, "SELECT selector_min(1.5, time) AS r FROM main"},
      {:raw, "SELECT selector_min('a', time) AS r FROM main"},
      {:raw, "SELECT selector_last(1, time) AS r FROM main"},
      {:raw, "SELECT selector_last(1.5, time)['time'] AS r FROM main"},
      {:raw, "SELECT selector_first('a', time)['value'] AS r FROM main"},
      {:raw, "SELECT selector_first(true, time)['value'] AS r FROM main"},
      {:raw, "SELECT selector_first(NULL, time)['value'] AS r FROM main"},
      {:raw, "SELECT selector_first(1, time)['time'] AS r FROM main"},
      {:raw, "SELECT selector_first(1, time) AS r FROM main"},
      {:raw, "SELECT selector_first(-1, time) AS r FROM main"},
      {:raw, "SELECT selector_first(1+1, time) AS r FROM main"},
      {:raw, "SELECT selector_first(1e3, time) AS r FROM main"},
      {:raw, "SELECT selector_max(n, time, 1) AS r FROM main"},
      {:raw, "SELECT selector_max(1, time) AS r FROM main WHERE false"},
      {:raw, "SELECT selector_max(n, -1) AS r FROM main"},
      {:raw, "SELECT selector_max(n, 1 + 1) AS r FROM main"},
      {:raw, "SELECT selector_max(n, 0.5) AS r FROM main"},
      {:raw, "SELECT selector_max(n, 1.0) AS r FROM main"},
      {:raw, "SELECT selector_max(n, time + 1) AS r FROM main"},
      {:raw, "SELECT selector_max(n + 1, time) AS r FROM main"},
      {:raw, "SELECT selector_max(1e3, time) AS r FROM main"},
      {:raw, "SELECT selector_max(9223372036854775808, time) AS r FROM main"},
      {:raw, "SELECT selector_max(n, 0x10) AS r FROM main"},
      {:raw, "SELECT selector_first(1e999, time) AS r FROM main"},
      {:raw, "SELECT selector_first(0x10, time) AS r FROM main"},
      {:raw, "SELECT selector_first(007, time) AS r FROM main"},
      {:raw, "SELECT selector_first(False, time) AS r FROM main"},
      {:raw, "SELECT selector_max(n, 1) AS r FROM main HAVING zzz > 1"},
      {:raw, "SELECT avg(DISTINCT +n) AS r FROM main"},
      {:raw, "SELECT avg(DISTINCT -n) AS r FROM main"},
      {:raw, "SELECT min(DISTINCT +n) AS r FROM main"},
      {:raw, "SELECT min(DISTINCT -n) AS r FROM main"},
      {:raw, "SELECT max(DISTINCT +n) AS r FROM main"},
      {:raw, "SELECT max(DISTINCT -n) AS r FROM main"},
      {:raw, "SELECT median(DISTINCT +n) AS r FROM main"},
      {:raw, "SELECT median(DISTINCT -n) AS r FROM main"},
      {:raw, "SELECT stddev(DISTINCT +n) AS r FROM main"},
      {:raw, "SELECT stddev(DISTINCT -n) AS r FROM main"},
      {:raw, "SELECT avg(DISTINCT n) AS r FROM main"},
      {:raw, "SELECT min(DISTINCT n) AS r FROM main"},
      {:raw, "SELECT max(DISTINCT n) AS r FROM main"},
      {:raw, "SELECT median(DISTINCT n) AS r FROM main"},
      {:raw, "SELECT stddev(DISTINCT n) AS r FROM main"},
      {:raw, "SELECT var(DISTINCT -n) AS r FROM main"},
      {:raw, "SELECT var(DISTINCT +n) AS r FROM main"},
      {:raw, "SELECT avg(DISTINCT n + 1) AS r FROM main"},
      {:raw, "SELECT avg(DISTINCT (-n)) AS r FROM main"},
      {:raw, "SELECT avg(DISTINCT - n) AS r FROM main"},
      {:raw, "SELECT avg(DISTINCT -1) AS r FROM main"},
      {:raw, "SELECT avg(DISTINCT +1) AS r FROM main"},
      {:raw, "SELECT avg(DISTINCT +x) AS r FROM main"},
      {:raw, "SELECT avg(DISTINCT -x) AS r FROM main"},
      {:raw, "SELECT min(distinct -s) AS r FROM main"},
      {:raw, "SELECT max(DISTINCT +s) AS r FROM main"},
      {:raw, "SELECT approx_distinct(DISTINCT +n) AS r FROM main"},
      {:raw, "SELECT avg(DISTINCT +time) AS r FROM main"},
      {:raw, "SELECT min(DISTINCT -time) AS r FROM main"},
      {:raw, "SELECT avg(DISTINCT +NULL) AS r FROM main"},
      {:raw, "SELECT avg(DISTINCT NOT n) AS r FROM main"},
      {:raw, "SELECT avg(DISTINCT CAST(n AS DOUBLE)) AS r FROM main"},
      {:raw, "SELECT avg(DISTINCT abs(n)) AS r FROM main"},
      {:raw, "SELECT host, count(*) FROM main WHERE false GROUP BY host ORDER BY m.host"},
      {:raw, "SELECT host FROM main WHERE false ORDER BY a.b.c"},
      {:raw, "SELECT host FROM main WHERE false GROUP BY m.host"},
      {:raw, "SELECT count(*) FROM main WHERE false ORDER BY m.host"},
      {:raw,
       "SELECT DISTINCT host, count(*) FROM main GROUP BY host HAVING count(*) > 3 ORDER BY host"},
      {:raw, "SELECT DISTINCT host FROM main HAVING host = 'h1' ORDER BY host"},
      {:raw, "SELECT DISTINCT host AS h FROM main GROUP BY host HAVING h = 'h1' ORDER BY h"},
      {:raw, "SELECT host, selector_max(1, time) AS r FROM main GROUP BY host ORDER BY host"},
      {:raw, "SELECT avg(DISTINCT -n) AS r FROM main GROUP BY host ORDER BY host"},
      {:raw, "SELECT avg(DISTINCT +n) AS r FROM main GROUP BY host ORDER BY host"},
      {:raw, "SELECT v FROM main WHERE 1 NOT LIKE host ORDER BY time"},
      {:raw, "SELECT v FROM main WHERE 1 LIKE host ORDER BY time"},
      {:raw, "SELECT v FROM main WHERE n LIKE host ORDER BY time"},
      {:raw, "SELECT selector_min(n, 1), selector_min(n, 1) FROM main"}
    ]
  end

  @doc "The cases refused of `syntax_refusable/0` of `SQLCatalogCases`."
  @spec syntax() :: [{atom(), binary()}]
  def syntax do
    [
      {:raw, "SELECT count(*, 1) FROM main"},
      {:raw, "SELECT n // 2 FROM main"},
      {:raw, "SELECT 'a' ~~ 'a'"},
      {:raw, "SELECT 'a' ~~* 'A'"},
      {:raw, "SELECT 'a' !~~ 'a'"},
      {:raw, "SELECT 'a' !~~* 'b'"},
      {:raw, "SELECT s ~~ 's%' FROM main WHERE n = 1"},
      {:raw, "SELECT current_time IS NOT NULL"},
      {:raw, "SELECT current_date IS NOT NULL"},
      {:raw, "SELECT current_timestamp IS NOT NULL"},
      {:raw, "SELECT current_time() IS NOT NULL"},
      {:raw, "SELECT timestamp '2020-01-01 00:00:00'"},
      {:raw, "SELECT timestamp with time zone '2020-01-01 00:00:00'"},
      {:raw, "SELECT timestamp without time zone '2020-01-01 00:00:00'"},
      {:raw, "SELECT timestamp(3) '2020-01-01 00:00:00'"},
      {:raw, "SELECT timestamp(3) with time zone '2020-01-01'"},
      {:raw, "SELECT timestamptz '2020-01-01'"},
      {:raw, "SELECT date '2020-01-01'"},
      {:raw, "SELECT time '10:00:00'"},
      {:raw, "SELECT time with time zone '10:00:00'"},
      {:raw, "SELECT datetime '2020-01-01 00:00:00'"},
      {:raw, "SELECT time(3) '10:00:00'"},
      {:raw,
       "SELECT n FROM main WHERE time > timestamp with time zone '2023-11-14 22:13:25' AND n = 1"},
      {:raw, "SELECT time - time AS d FROM main WHERE n = 1"},
      {:raw, "SELECT max(time) - min(time) AS d FROM main"},
      {:raw, "SELECT count(*) AS c FROM main WHERE time - time = interval '0'"},
      {:raw, "SELECT time - interval '1 second' AS t FROM main WHERE n = 1"},
      {:raw, "SELECT host on FROM main WHERE n = 1"},
      {:raw, "SELECT host join FROM main WHERE n = 1"},
      {:raw, "SELECT v FROM main WHERE n IN (1 == 1)"},
      {:raw, "SELECT n <=> 1 AS r FROM main ORDER BY time"},
      {:raw, "SELECT n <=> NULL AS r FROM main ORDER BY time"},
      {:raw, "SELECT v FROM main WHERE n <=> NULL"},
      {:raw, "SELECT v FROM main WHERE NOT n <=> 1 ORDER BY time LIMIT 2"},
      {:raw, "SELECT n <=> FROM main"},
      {:raw, "SELECT DISTINCT ALL n FROM main ORDER BY n"},
      {:raw, "SELECT ALL n FROM main UNION ALL SELECT ALL n FROM main ORDER BY n"},
      {:raw, "SELECT * EXCLUDE (n, time) FROM main ORDER BY host, v LIMIT 1"},
      {:raw, "SELECT * EXCLUDE n FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT * EXCEPT (n) FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT * EXCEPT n FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT * REPLACE (n + 1 AS n) FROM main ORDER BY time LIMIT 1"},
      {:raw, "SELECT n FROM (main CROSS JOIN ping) ORDER BY time"},
      {:raw, "SELECT 0x10 AS r FROM main LIMIT 1"},
      {:raw, "SELECT 0x AS r FROM main LIMIT 1"},
      {:raw, "SELECT 0x10 + 1 AS r FROM main LIMIT 1"},
      {:raw, "VALUES (1)"},
      {:raw, "VALUES (1, 'a'), (2, 'b')"},
      {:raw, "SELECT * FROM (VALUES (1), (2)) AS t"},
      {:raw, "VALUES (2), (1) ORDER BY column1 DESC LIMIT 1"},
      {:raw, "SELECT main.n, ping.v FROM main, ping ORDER BY main.n"},
      {:raw, "SELECT n FROM main, ping, mext ORDER BY n"},
      {:raw, "SELECT 1 N'a' z"},
      {:raw, "SELECT 1 X'AB' z"},
      {:raw, "create index i on m (a)"},
      {:raw, "desc 'a'"},
      {:raw, "drop extension a, b"},
      {:raw, "insert into"},
      {:raw, "insert into information_schema.tables values (1)"},
      {:raw, "insert or replace into m values (1)"},
      {:raw, "insert overwrite m values (1)"},
      {:raw, "select 1 union table a"},
      {:raw, "update information_schema.tables set v = 1"},
      {:raw, "attach database 'd' as e"},
      {:raw, "create trigger t before insert on m"},
      {:raw, "desc 'a b'"},
      {:raw, "grant select () on m to u"},
      {:raw, "merge into m as a using t as b on a.x = b.x when matched then update set x = 1"},
      {:raw, "merge into m using (select 1) as t on true"},
      {:raw,
       "merge into m using t on true when matched then delete when not matched then insert values (1)"},
      {:raw, "merge into m using t on true when not matched then insert (a) values (1)"},
      {:raw, "merge into m using t on x = 1"},
      {:raw, "UPDATE main SET n = (SELECT 1)"},
      {:raw, "UPDATE main SET n = CASE WHEN n > 1 THEN 1 END"},
      {:raw, "UPDATE main SET n = interval '1 hour'"},
      {:raw, "UPDATE main SET n = 1 FROM ping"},
      {:raw, "UPDATE zzz SET n = (SELECT 1)"},
      {:raw, "GRANT SELECT ON ALL VIEWS IN SCHEMA iox TO u"},
      {:raw, "GRANT SELECT ON PROCEDURE p TO u"},
      {:raw, "GRANT SELECT ON m TO PUBLIC, u"},
      {:raw, "GRANT SELECT ON m TO PUBLIC, PUBLIC"},
      {:raw, "GRANT SELECT ON m TO PUBLIC.x"},
      {:raw, "GRANT SELECT ON FUTURE TABLES IN SCHEMA s TO u"},
      {:raw, "GRANT SELECT ON WAREHOUSE w TO u"},
      {:raw, "GRANT SELECT ON USER w TO u"},
      {:raw, "GRANT SELECT ON ALL VIEWS"},
      {:raw, "GRANT SELECT ON ALL VIEWS IN SCHEMA"},
      {:raw, "GRANT SELECT ON ALL VIEWS IN SCHEMA s"},
      {:raw, "GRANT SELECT ON ALL VIEWS IN SCHEMA s,"},
      {:raw, "GRANT SELECT ON PROCEDURE"},
      {:raw, "GRANT SELECT ON PROCEDURE p"},
      {:raw, "GRANT SELECT ON PROCEDURE p,"},
      {:raw, "GRANT SELECT ON PROCEDURE p TO"},
      {:raw, "grant select on all materialized views in schema s to u"},
      {:raw, "grant select on future external tables in schema s, t to u"},
      {:raw, "grant select on future schemas in database d to u"},
      {:raw, "grant select on future views in schema s to u"},
      {:raw, "grant select on all views in schema s, t.u to u"},
      {:raw, "grant select on procedure p, q to u"},
      {:raw, "grant select on integration i to u"},
      {:raw, "grant select on connection c to u"},
      {:raw, "grant select on future sequences in schema s to u"},
      {:raw, "grant select on all external tables in schema s to u"},
      {:raw, "grant select on future views in schema"},
      {:raw, "grant select on future views in schema s,"},
      {:raw, "grant select on future views in schema s"},
      {:raw, "grant select on future schemas in database"},
      {:raw, "grant select on future schemas in database d"},
      {:raw, "grant select on future schemas in database d,"},
      {:raw, "grant select on future views"},
      {:raw, "grant select on future"},
      {:raw, "grant select on all external tables in schema"},
      {:raw, "grant select on all external tables"},
      {:raw, "grant select on all materialized views in schema"},
      {:raw, "grant select on all materialized"},
      {:raw, "grant select on warehouse"},
      {:raw, "grant select on warehouse w"},
      {:raw, "grant select on warehouse w,"},
      {:raw, "grant select on user"},
      {:raw, "grant select on user u"},
      {:raw, "grant select on user u,"},
      {:raw, "grant select on user to u"},
      {:raw, "grant select on procedure to u"},
      {:raw, "grant select on connection to u"},
      {:raw, "grant select on integration to u"},
      {:raw, "grant select on all views in schema to u"},
      {:raw, "grant select on all views in schema iox, to u"},
      {:raw, "grant select on function f, g to u"},
      {:raw, "grant select on function f(int) to u"},
      {:raw, "grant select on function f.g, h.i to u"},
      {:raw, "grant select on m to u, public, v"},
      {:raw, "deny select on m to public, u"},
      {:raw, "grant select on function f,"},
      {:raw, "DESC EXTENDED \"main\""},
      {:raw, "DESC extended.main"},
      {:raw, "DESC extended.x"},
      {:raw, "DESC \"extended\""},
      {:raw, "DESC EXTENDED information_schema.tables"},
      {:raw, "DESC EXTENDED system.queries"},
      {:raw, "update main set v = 1 from ping"},
      {:raw, "update main set v = 1 from ping where ping.v = 1"},
      {:raw,
       "SELECT n FROM main WHERE time IS DISTINCT FROM '2023-11-14T22:13:20Z' ORDER BY time"},
      {:raw, "update main as \"M\" set v = 1"},
      {:raw, "update main \"M\" set v = 1"},
      {:raw, "update main from t set v = 1"},
      {:raw, "update main join t on true set v = 1"},
      {:raw, "update main inner join t set v = 1"},
      {:raw, "update main cross join t set v = 1"},
      {:raw, "update main left join t set v = 1"},
      {:raw, "update main m from t set v = 1"},
      {:raw, "update main set 'a' = 1"},
      {:raw, "update main set v = 1 from t"},
      {:raw, "update main set v = 1 from t, u"},
      {:raw, "update main set v = 1 from t as x"},
      {:raw, "update main set v = 1 from t x"},
      {:raw, "update main set v = 1 from (select 1)"},
      {:raw, "update main set v = 1 from t join u on true"},
      {:raw, "update main set v = 1 from t on true"},
      {:raw, "update main set v = 1 from t using x"},
      {:raw, "update main set v = 1 where n in (select 1)"},
      {:raw, "update main set v = 1 where n is foo"},
      {:raw, "update main set v = 1 where n is"},
      {:raw, "update main set v = 1 where n xor 1"},
      {:raw, "update main set v = 1 where n div 1"},
      {:raw, "update main set v = 1 where n mod 1"},
      {:raw, "update main set v = 1 where n overlaps 1"},
      {:raw, "update main set v = 1 where s rlike 'a'"},
      {:raw, "update main set v = 1 where s regexp 'a'"},
      {:raw, "update main set v = 1 where s similar to 'a'"},
      {:raw, "update main set v = 1 where n isnull"},
      {:raw, "update main set v = 1 where n notnull"},
      {:raw, "update main set v = 1 where n at 1"},
      {:raw, "update main set v = 1 where s collate x"},
      {:raw, "update main set v = 1 where n match 1"},
      {:raw, "update main set v = 1 where n operator(+) 1"},
      {:raw, "update main set v = X'ff'"},
      {:raw, "update main set v = N'a'"},
      {:raw, "update main set v = ?"},
      {:raw, "update main set v = :a"},
      {:raw, "update main set v = @a"},
      {:raw, "update main set v = [1]"},
      {:raw, "update main set v = {a}"},
      {:raw, "update main set v = date '2020-01-01'"},
      {:raw, "update main set v = timestamp '2020-01-01'"},
      {:raw, "update main set v = interval '1 day'"},
      {:raw, "update main set v = case when true then 1 end"},
      {:raw, "update main set v = exists (select 1)"},
      {:raw, "update main set v = array[1]"},
      {:raw, "update main set v = row(1, 2)"},
      {:raw, "update main set v = current_date"},
      {:raw, "update main set v = (1, 2)"},
      {:raw, "update main set v = 0x10"},
      {:raw, "update main set v = count(distinct n)"},
      {:raw, "update main set v = count(all n)"},
      {:raw, "update main set v = abs(1) over (partition by n)"},
      {:raw, "update main set v = abs(1) filter (where true)"},
      {:raw, "update main set v = abs(1) within group (order by n)"},
      {:raw, "update main set v = abs(1) ignore nulls"},
      {:raw, "update main set v = abs(1) respect nulls"},
      {:raw, "update main set v = cast(1 as varchar(10))"},
      {:raw, "update main set v = cast(1 as decimal(10, 2))"},
      {:raw, "update main set v = cast(1 as decimal(10))"},
      {:raw, "update main set v = cast(1 as timestamp with time zone)"},
      {:raw, "update main set v = cast(1 as float)"},
      {:raw, "update main set v = cast(1 as real)"},
      {:raw, "update main set v = cast(1 as unsigned)"},
      {:raw, "update main set v = main.*"},
      {:raw, "update main set v = 1 where abs(n)"},
      {:raw, "update main set v = 1 where -n"},
      {:raw, "update main set v = 1 where (n, 1)"},
      {:raw, "update mext set u = 1 where -u"},
      {:raw, "update main set v = 1 where s not rlike 'a'"},
      {:raw, "update main set v = 1 where s not regexp 'a'"},
      {:raw, "update main set v = 1 where s not similar to 'a'"},
      {:raw, "update main set v = 1 where n not xor 1"},
      {:raw, "update main set v = 1 where s like 'a' escape 1"},
      {:raw, "update main set v = 1 where s like 'a' escape x"},
      {:raw, "update main set v = cast(1 as interval)"},
      {:raw, "update main set v = cast(1 as character varying)"},
      {:raw, "update main set v = cast(1 as national character)"},
      {:raw, "update main set v = cast(1 as bit)"},
      {:raw, "update main set v = cast(1 as character)"},
      {:raw, "update main set v = cast(1 as timestamp without time zone)"},
      {:raw, "update main set v = cast(1 as time with time zone)"},
      {:raw, "update main set v = $"},
      {:raw, "update main set v = 1 where host.a"},
      {:raw, "update main set v = 1 where time.a"},
      {:raw, "update main set v = 1 where 12345678901234567890"},
      {:raw, "update main set v = 1 where 1e400"},
      {:raw, "update main set v = 1 where 'a$b'"},
      {:raw, "update mext set b = u + i"},
      {:raw, "update mext set b = u - i"},
      {:raw, "update main set v = $1 + abs(s)"},
      {:raw, "update main set v = abs(s) + $1"},
      {:raw, "update main set v = $1 is distinct from abs(s)"},
      {:raw, "update main set v = abs(s) is distinct from $1"},
      {:raw, "update main set v = coalesce(host, 1)"},
      {:raw, "update main set v = coalesce(n, host)"},
      {:raw, "update main set v = greatest(host, n)"},
      {:raw, "update main set b = (n, 1) = (n, 1)"},
      {:raw, "update main set v = (n, 1)"},
      {:raw, "update main set v = (abs(s), 1)"},
      {:raw, "update main set v = count()"},
      {:raw, "update main set v = sum(*)"},
      {:raw, "update main set v = abs(*)"},
      {:raw, "update main set v = log(1, 2, 3)"},
      {:raw, "update main set v = substr('a')"},
      {:raw, "update main set b = (s like 'a' escape abs(s))"},
      {:raw, "update main set v = +(n & 1)"},
      {:raw, "update main set v = n & 1"},
      {:raw, "update main set v = n | 1"},
      {:raw, "update main set v = n ^ 1"},
      {:raw, "update main set v = n << 1"},
      {:raw, "update main set v = n >> 1"},
      {:raw, "update main set v = n # 1"},
      {:raw, "update main set v = n @> 1"},
      {:raw, "update main set v = n -> 1"},
      {:raw, "update main set v = 1 where abs(cast(1 as varchar(10)))"},
      {:raw, "update main set v = 1 where (n + $1)"},
      {:raw, "update main set v = 1 where (abs(s) + $1)"},
      {:raw, "update main set v = 1 where abs(s) + $1"},
      {:raw, "update main set v = 1 where (+(n & 1))"},
      {:raw, "update main set v = 1 where n & 1"},
      {:raw, "update main set v = 1 where +(n & 1)"},
      {:raw, "update main set v = 1 where cast(1 as varchar(10))"},
      {:raw, "update main set v = 1 where coalesce(host, 1)"},
      {:raw, "update main set v = 1 where coalesce(n, host)"},
      {:raw, "update main set v = 1 where greatest(s, 1)"},
      {:raw, "update main set v = 1 where time - time"},
      {:raw, "update main set v = 1 where now() - time"},
      {:raw, "update main set v = 1 where now()"},
      {:raw, "update main set v = 1 where cast(n as bigint)"},
      {:raw, "update main set v = 1 where length(s)"},
      {:raw, "update main set v = 1 where abs(1)"},
      {:raw, "update main set v = 1 where 1 + 1"},
      {:raw, "update main set v = 1 where n + 1"},
      {:raw, "update main set v = 1 where s || 1"},
      {:raw, "update main set v = v. + 1"},
      {:raw, "update main set v = v.)"},
      {:raw, "update main set v = v.'a'"},
      {:raw, "update main set v = v.,"},
      {:raw, "update main set v = abs(v.)"},
      {:raw, "update main set v = +date_trunc('day', time)"},
      {:raw, "update main set v = +approx_distinct(n)"},
      {:raw, "update main set v = +var_pop(n)"},
      {:raw, "update main set v = +stddev_pop(n)"},
      {:raw, "update main set v = +date_bin('1 day', time)"},
      {:raw, "update main set v = date_trunc('day', time)"},
      {:raw, "update main set b = date_trunc('day', time)"},
      {:raw, "update main set b = approx_distinct(n)"},
      {:raw, "update main set b = var_pop(n)"},
      {:raw, "update main set b = locf(x)"},
      {:raw, "update main set b = interpolate(x)"},
      {:raw, "update main set v. = 1"},
      {:raw, "update main set main. = 1"},
      {:raw, "update main set v.) = 1"},
      {:raw, "update main set main.v. = 1"},
      {:raw, "insert into main select 1"},
      {:raw, "insert into main (select 1)"},
      {:raw, "insert into main with a as (select 1) select * from a"},
      {:raw, "insert into main values (1, 2"},
      {:raw, "insert into main values 1"},
      {:raw, "insert into main values (1) (2)"},
      {:raw, "insert into main values (1) foo"},
      {:raw, "insert into main (v, n"},
      {:raw, "insert into main (v, n values (1, 2)"},
      {:raw, "insert into main (v) , "},
      {:raw, "insert into main (v) +"},
      {:raw, "insert into main +"},
      {:raw, "insert into main (v) = 1"},
      {:raw, "insert into main (1) values (1)"},
      {:raw, "insert into main () values (1)"},
      {:raw, "insert into main (v, ) values (1, 2)"},
      {:raw, "insert into main (v,, n) values (1, 2)"},
      {:raw, "insert into main (\"v\") values (1)"},
      {:raw, "insert into main values ()"},
      {:raw, "insert into main values (,)"},
      {:raw, "insert or replace into main values (1)"},
      {:raw, "insert overwrite main values (1)"},
      {:raw, "insert ignore into main values (1)"},
      {:raw, "update main set v = abss(1)"},
      {:raw, "update main set v = abs(abss(1))"},
      {:raw, "update main set v = \"abss\"(1)"},
      {:raw, "update main set v = m.abs(1)"},
      {:raw, "update main set v = main.lower(s)"},
      {:raw, "update main set v = a.b.abs(1)"}
    ]
  end

  @doc "The cases refused of `catalog_refusable/0` of `SQLCatalogCases`."
  @spec catalog() :: [{atom(), binary()}]
  def catalog do
    [
      {:raw, "SHOW COLUMNS FROM system.nosuch"},
      {:raw, "SHOW COLUMNS"},
      {:raw, "SHOW COLUMNS FROM"},
      {:raw, "SHOW COLUMNS FROM main WHERE column_name = 'n'"},
      {:raw, "SHOW COLUMNS FROM \"main\""},
      {:raw, "SHOW SCHEMAS"},
      {:raw, "SHOW TABLES FROM iox"},
      {:raw, "SHOW VARIABLE x"},
      {:raw, "SHOW FULL COLUMNS FROM main"},
      {:raw, "SELECT * FROM system.nosuch"}
    ]
  end
end
